## Lossless raw Discord models in the `application` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ActivitiesAttachmentResponse* = object ## Lossless raw representation of OpenAPI schema `ActivitiesAttachmentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActivityActionTypes* = object ## Lossless raw representation of OpenAPI schema `ActivityActionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActivityInstanceCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `ActivityInstanceCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAttachmentOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAttachmentOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAttachmentOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAttachmentOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAutocompleteCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAutocompleteCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandBooleanOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandBooleanOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandBooleanOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandBooleanOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandChannelOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandChannelOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandChannelOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandChannelOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandCreateRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandHandler* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandHandler`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandIntegerOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandIntegerOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandIntegerOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandIntegerOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandInteractionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandInteractionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandMentionableOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandMentionableOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandMentionableOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandMentionableOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandNumberOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandNumberOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandNumberOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandNumberOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionIntegerChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionIntegerChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionIntegerChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionIntegerChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionNumberChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionNumberChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionNumberChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionNumberChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionStringChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionStringChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionStringChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionStringChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPatchRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPermission* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPermission`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPermissionType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPermissionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandRoleOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandRoleOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandRoleOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandRoleOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandStringOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandStringOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandStringOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandStringOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandGroupOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandGroupOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandGroupOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandGroupOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUpdateRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUpdateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUserOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUserOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUserOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUserOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationEventWebhooksStatus* = object ## Lossless raw representation of OpenAPI schema `ApplicationEventWebhooksStatus`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationExplicitContentFilterTypes* = object ## Lossless raw representation of OpenAPI schema `ApplicationExplicitContentFilterTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationFormPartial* = object ## Lossless raw representation of OpenAPI schema `ApplicationFormPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIdentityProviderAuthType* = object ## Lossless raw representation of OpenAPI schema `ApplicationIdentityProviderAuthType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIncomingWebhookResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationIncomingWebhookResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationType* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationTypeConfiguration* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationTypeConfiguration`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationTypeConfigurationResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationTypeConfigurationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationOAuth2InstallParams* = object ## Lossless raw representation of OpenAPI schema `ApplicationOAuth2InstallParams`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationOAuth2InstallParamsResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationOAuth2InstallParamsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationRoleConnectionsMetadataItemRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationRoleConnectionsMetadataItemRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationRoleConnectionsMetadataItemResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationRoleConnectionsMetadataItemResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationTypes* = object ## Lossless raw representation of OpenAPI schema `ApplicationTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationUserRoleConnectionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationUserRoleConnectionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementOwnerTypes* = object ## Lossless raw representation of OpenAPI schema `EntitlementOwnerTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementResponse* = object ## Lossless raw representation of OpenAPI schema `EntitlementResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementTenantFulfillmentStatusResponse* = object ## Lossless raw representation of OpenAPI schema `EntitlementTenantFulfillmentStatusResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementTypes* = object ## Lossless raw representation of OpenAPI schema `EntitlementTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SubscriptionResponse* = object ## Lossless raw representation of OpenAPI schema `SubscriptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SubscriptionResponseStatusType* = object ## Lossless raw representation of OpenAPI schema `SubscriptionResponseStatusType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
