## Lossless raw Discord models in the `application` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ActivitiesAttachmentResponse* = object ## Lossless raw representation of OpenAPI schema `ActivitiesAttachmentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActivityActionTypes* = object ## Lossless raw representation of OpenAPI schema `ActivityActionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActivityInstanceCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `ActivityInstanceCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAttachmentOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAttachmentOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandAttachmentOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAttachmentOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAttachmentOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandAttachmentOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandAutocompleteCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandAutocompleteCallbackRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandAutocompleteCallbackRequest/properties/data/x-discord-union`
    ##   uses `exclusive-union` with `one-of`.
    ## - `#/components/schemas/ApplicationCommandAutocompleteCallbackRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandBooleanOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandBooleanOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandBooleanOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandBooleanOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandBooleanOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandBooleanOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandChannelOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandChannelOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandChannelOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandChannelOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandChannelOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandChannelOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandCreateRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandHandler* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandHandler`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandIntegerOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandIntegerOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandIntegerOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandIntegerOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandIntegerOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandIntegerOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandInteractionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandInteractionMetadataResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandInteractionMetadataResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandMentionableOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandMentionableOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandMentionableOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandMentionableOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandMentionableOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandMentionableOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandNumberOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandNumberOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandNumberOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandNumberOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandNumberOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandNumberOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionIntegerChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionIntegerChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionIntegerChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionIntegerChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionNumberChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionNumberChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionNumberChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionNumberChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionStringChoice* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionStringChoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionStringChoiceResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionStringChoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandOptionType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandOptionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPatchRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandPatchRequestPartial`
    ##   uses `patch-object` with `unset-null-value`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPermission* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPermission`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandPermissionType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandPermissionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandRoleOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandRoleOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandRoleOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandRoleOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandRoleOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandRoleOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandStringOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandStringOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandStringOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandStringOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandStringOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandStringOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandGroupOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandGroupOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandSubcommandGroupOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandGroupOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandGroupOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandSubcommandGroupOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandSubcommandOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandSubcommandOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandSubcommandOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandSubcommandOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandType* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUpdateRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUpdateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUserOption* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUserOption`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandUserOption/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationCommandUserOptionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationCommandUserOptionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationCommandUserOptionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationEventWebhooksStatus* = object ## Lossless raw representation of OpenAPI schema `ApplicationEventWebhooksStatus`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationExplicitContentFilterTypes* = object ## Lossless raw representation of OpenAPI schema `ApplicationExplicitContentFilterTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationFormPartial* = object ## Lossless raw representation of OpenAPI schema `ApplicationFormPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationFormPartial/properties/event_webhooks_status/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    ## - `#/components/schemas/ApplicationFormPartial/properties/event_webhooks_types/items/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIdentityProviderAuthType* = object ## Lossless raw representation of OpenAPI schema `ApplicationIdentityProviderAuthType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIncomingWebhookResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationIncomingWebhookResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationIncomingWebhookResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationType* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationTypeConfiguration* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationTypeConfiguration`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationIntegrationTypeConfigurationResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationIntegrationTypeConfigurationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationOAuth2InstallParams* = object ## Lossless raw representation of OpenAPI schema `ApplicationOAuth2InstallParams`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationOAuth2InstallParams/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/ApplicationOAuth2InstallParams/properties/scopes/items/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationOAuth2InstallParamsResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationOAuth2InstallParamsResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationOAuth2InstallParamsResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/ApplicationOAuth2InstallParamsResponse/properties/scopes/items/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ApplicationResponse/properties/flags_new`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationRoleConnectionsMetadataItemRequest* = object ## Lossless raw representation of OpenAPI schema `ApplicationRoleConnectionsMetadataItemRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationRoleConnectionsMetadataItemResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationRoleConnectionsMetadataItemResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationTypes* = object ## Lossless raw representation of OpenAPI schema `ApplicationTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ApplicationUserRoleConnectionResponse* = object ## Lossless raw representation of OpenAPI schema `ApplicationUserRoleConnectionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementOwnerTypes* = object ## Lossless raw representation of OpenAPI schema `EntitlementOwnerTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementResponse* = object ## Lossless raw representation of OpenAPI schema `EntitlementResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementTenantFulfillmentStatusResponse* = object ## Lossless raw representation of OpenAPI schema `EntitlementTenantFulfillmentStatusResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntitlementTypes* = object ## Lossless raw representation of OpenAPI schema `EntitlementTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SubscriptionResponse* = object ## Lossless raw representation of OpenAPI schema `SubscriptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SubscriptionResponseStatusType* = object ## Lossless raw representation of OpenAPI schema `SubscriptionResponseStatusType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
