## Lossless raw Discord models in the `automod` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  AutomodActionType* = object ## Lossless raw representation of OpenAPI schema `AutomodActionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AutomodEventType* = object ## Lossless raw representation of OpenAPI schema `AutomodEventType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AutomodKeywordPresetType* = object ## Lossless raw representation of OpenAPI schema `AutomodKeywordPresetType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AutomodTriggerType* = object ## Lossless raw representation of OpenAPI schema `AutomodTriggerType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
