## Lossless raw Discord models in the `channel` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ChannelFollowerResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelFollowerResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelFollowerWebhookResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelFollowerWebhookResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwriteRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwriteRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwriteResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwriteResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwrites* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwrites`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectDefaultValue* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectDefaultValue`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectDefaultValueResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectDefaultValueResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelTypes* = object ## Lossless raw representation of OpenAPI schema `ChannelTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ForumLayout* = object ## Lossless raw representation of OpenAPI schema `ForumLayout`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ForumTagResponse* = object ## Lossless raw representation of OpenAPI schema `ForumTagResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadAutoArchiveDuration* = object ## Lossless raw representation of OpenAPI schema `ThreadAutoArchiveDuration`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadMemberResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSearchResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadSearchResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSearchTagSetting* = object ## Lossless raw representation of OpenAPI schema `ThreadSearchTagSetting`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSortOrder* = object ## Lossless raw representation of OpenAPI schema `ThreadSortOrder`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSortingMode* = object ## Lossless raw representation of OpenAPI schema `ThreadSortingMode`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadsResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
