## Lossless raw Discord models in the `channel` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ChannelFollowerResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelFollowerResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelFollowerWebhookResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelFollowerWebhookResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelFollowerWebhookResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwriteRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwriteRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelPermissionOverwriteRequest/properties/allow`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/ChannelPermissionOverwriteRequest/properties/deny`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwriteResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwriteResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelPermissionOverwriteResponse/properties/allow`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/ChannelPermissionOverwriteResponse/properties/deny`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelPermissionOverwrites* = object ## Lossless raw representation of OpenAPI schema `ChannelPermissionOverwrites`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelSelectComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/ChannelSelectComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelSelectComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/ChannelSelectComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelSelectComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectDefaultValue* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectDefaultValue`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelSelectDefaultValue/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelSelectDefaultValueResponse* = object ## Lossless raw representation of OpenAPI schema `ChannelSelectDefaultValueResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ChannelSelectDefaultValueResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ChannelTypes* = object ## Lossless raw representation of OpenAPI schema `ChannelTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ForumLayout* = object ## Lossless raw representation of OpenAPI schema `ForumLayout`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ForumTagResponse* = object ## Lossless raw representation of OpenAPI schema `ForumTagResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadAutoArchiveDuration* = object ## Lossless raw representation of OpenAPI schema `ThreadAutoArchiveDuration`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadMemberResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ThreadResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/ThreadResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSearchResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadSearchResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSearchTagSetting* = object ## Lossless raw representation of OpenAPI schema `ThreadSearchTagSetting`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSortOrder* = object ## Lossless raw representation of OpenAPI schema `ThreadSortOrder`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadSortingMode* = object ## Lossless raw representation of OpenAPI schema `ThreadSortingMode`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThreadsResponse* = object ## Lossless raw representation of OpenAPI schema `ThreadsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
