## Lossless raw Discord models in the `common` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ActionTypes* = object ## Lossless raw representation of OpenAPI schema `ActionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AfkTimeouts* = object ## Lossless raw representation of OpenAPI schema `AfkTimeouts`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AuthorType* = object ## Lossless raw representation of OpenAPI schema `AuthorType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AvailableLocalesEnum* = object ## Lossless raw representation of OpenAPI schema `AvailableLocalesEnum`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BaseCreateMessageCreateRequest* = object ## Lossless raw representation of OpenAPI schema `BaseCreateMessageCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BasicApplicationResponseWithBot* = object ## Lossless raw representation of OpenAPI schema `BasicApplicationResponseWithBot`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BasicGuildMemberResponse* = object ## Lossless raw representation of OpenAPI schema `BasicGuildMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BasicMessageResponse* = object ## Lossless raw representation of OpenAPI schema `BasicMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BlockMessageAction* = object ## Lossless raw representation of OpenAPI schema `BlockMessageAction`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/BlockMessageAction/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BlockMessageActionMetadata* = object ## Lossless raw representation of OpenAPI schema `BlockMessageActionMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BlockMessageActionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `BlockMessageActionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BlockMessageActionResponse* = object ## Lossless raw representation of OpenAPI schema `BlockMessageActionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/BlockMessageActionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BotAccountPatchRequest* = object ## Lossless raw representation of OpenAPI schema `BotAccountPatchRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BotAddGuildMemberRequest* = object ## Lossless raw representation of OpenAPI schema `BotAddGuildMemberRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BulkBanUsersRequest* = object ## Lossless raw representation of OpenAPI schema `BulkBanUsersRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BulkBanUsersResponse* = object ## Lossless raw representation of OpenAPI schema `BulkBanUsersResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  BulkLobbyMemberRequest* = object ## Lossless raw representation of OpenAPI schema `BulkLobbyMemberRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/BulkLobbyMemberRequest/properties/flags/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ByNWeekday* = object ## Lossless raw representation of OpenAPI schema `ByNWeekday`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ByNWeekdayResponse* = object ## Lossless raw representation of OpenAPI schema `ByNWeekdayResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ConnectedAccountGuildResponse* = object ## Lossless raw representation of OpenAPI schema `ConnectedAccountGuildResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ConnectedAccountIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `ConnectedAccountIntegrationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ConnectedAccountProviders* = object ## Lossless raw representation of OpenAPI schema `ConnectedAccountProviders`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ConnectedAccountResponse* = object ## Lossless raw representation of OpenAPI schema `ConnectedAccountResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ConnectedAccountVisibility* = object ## Lossless raw representation of OpenAPI schema `ConnectedAccountVisibility`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateEntitlementRequestData* = object ## Lossless raw representation of OpenAPI schema `CreateEntitlementRequestData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateForumThreadRequest* = object ## Lossless raw representation of OpenAPI schema `CreateForumThreadRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateGroupDMInviteRequest* = object ## Lossless raw representation of OpenAPI schema `CreateGroupDMInviteRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateGuildChannelRequest* = object ## Lossless raw representation of OpenAPI schema `CreateGuildChannelRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CreateGuildChannelRequest/properties/type/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateGuildInviteRequest* = object ## Lossless raw representation of OpenAPI schema `CreateGuildInviteRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CreateGuildInviteRequest/properties/target_type/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateOrUpdateThreadTagRequest* = object ## Lossless raw representation of OpenAPI schema `CreateOrUpdateThreadTagRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreatePrivateChannelRequest* = object ## Lossless raw representation of OpenAPI schema `CreatePrivateChannelRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateRoleRequest* = object ## Lossless raw representation of OpenAPI schema `CreateRoleRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CreateRoleRequest/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateTextThreadWithMessageRequest* = object ## Lossless raw representation of OpenAPI schema `CreateTextThreadWithMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateTextThreadWithoutMessageRequest* = object ## Lossless raw representation of OpenAPI schema `CreateTextThreadWithoutMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CreateTextThreadWithoutMessageRequest/properties/type/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreatedThreadResponse* = object ## Lossless raw representation of OpenAPI schema `CreatedThreadResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CreatedThreadResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/CreatedThreadResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CustomClientThemeResponse* = object ## Lossless raw representation of OpenAPI schema `CustomClientThemeResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CustomClientThemeShareRequest* = object ## Lossless raw representation of OpenAPI schema `CustomClientThemeShareRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultKeywordListTriggerMetadata* = object ## Lossless raw representation of OpenAPI schema `DefaultKeywordListTriggerMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultKeywordListTriggerMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `DefaultKeywordListTriggerMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultKeywordListUpsertRequest* = object ## Lossless raw representation of OpenAPI schema `DefaultKeywordListUpsertRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/DefaultKeywordListUpsertRequest/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultKeywordListUpsertRequestPartial* = object ## Lossless raw representation of OpenAPI schema `DefaultKeywordListUpsertRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/DefaultKeywordListUpsertRequestPartial/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultKeywordRuleResponse* = object ## Lossless raw representation of OpenAPI schema `DefaultKeywordRuleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/DefaultKeywordRuleResponse/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DefaultReactionEmojiResponse* = object ## Lossless raw representation of OpenAPI schema `DefaultReactionEmojiResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  DiscordIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `DiscordIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/DiscordIntegrationResponse/properties/scopes/items/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    ## - `#/components/schemas/DiscordIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataExternal* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataExternal`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataExternalResponse* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataExternalResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataStageInstance* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataStageInstance`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataStageInstanceResponse* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataStageInstanceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataVoice* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataVoice`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EntityMetadataVoiceResponse* = object ## Lossless raw representation of OpenAPI schema `EntityMetadataVoiceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  Error* = object ## Lossless raw representation of OpenAPI schema `Error`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ErrorDetails* = object ## Lossless raw representation of OpenAPI schema `ErrorDetails`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ErrorResponse* = object ## Lossless raw representation of OpenAPI schema `ErrorResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ExternalConnectionIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `ExternalConnectionIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ExternalConnectionIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ExternalScheduledEventCreateRequest* = object ## Lossless raw representation of OpenAPI schema `ExternalScheduledEventCreateRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ExternalScheduledEventCreateRequest/properties/entity_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ExternalScheduledEventPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `ExternalScheduledEventPatchRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ExternalScheduledEventPatchRequestPartial`
    ##   uses `patch-object` with `unset-null-value`.
    ## - `#/components/schemas/ExternalScheduledEventPatchRequestPartial/properties/entity_type/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ExternalScheduledEventResponse* = object ## Lossless raw representation of OpenAPI schema `ExternalScheduledEventResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ExternalScheduledEventResponse/properties/entity_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FileUploadComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `FileUploadComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FileUploadComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/FileUploadComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FlagToChannelAction* = object ## Lossless raw representation of OpenAPI schema `FlagToChannelAction`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FlagToChannelAction/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FlagToChannelActionMetadata* = object ## Lossless raw representation of OpenAPI schema `FlagToChannelActionMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FlagToChannelActionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `FlagToChannelActionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FlagToChannelActionResponse* = object ## Lossless raw representation of OpenAPI schema `FlagToChannelActionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FlagToChannelActionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FriendInviteResponse* = object ## Lossless raw representation of OpenAPI schema `FriendInviteResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FriendInviteResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubAuthor* = object ## Lossless raw representation of OpenAPI schema `GithubAuthor`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCheckApp* = object ## Lossless raw representation of OpenAPI schema `GithubCheckApp`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCheckPullRequest* = object ## Lossless raw representation of OpenAPI schema `GithubCheckPullRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCheckRun* = object ## Lossless raw representation of OpenAPI schema `GithubCheckRun`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCheckRunOutput* = object ## Lossless raw representation of OpenAPI schema `GithubCheckRunOutput`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCheckSuite* = object ## Lossless raw representation of OpenAPI schema `GithubCheckSuite`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubComment* = object ## Lossless raw representation of OpenAPI schema `GithubComment`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubCommit* = object ## Lossless raw representation of OpenAPI schema `GithubCommit`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubDiscussion* = object ## Lossless raw representation of OpenAPI schema `GithubDiscussion`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubIssue* = object ## Lossless raw representation of OpenAPI schema `GithubIssue`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubRelease* = object ## Lossless raw representation of OpenAPI schema `GithubRelease`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubRepository* = object ## Lossless raw representation of OpenAPI schema `GithubRepository`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubReview* = object ## Lossless raw representation of OpenAPI schema `GithubReview`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubUser* = object ## Lossless raw representation of OpenAPI schema `GithubUser`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GithubWebhook* = object ## Lossless raw representation of OpenAPI schema `GithubWebhook`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GroupDMInviteResponse* = object ## Lossless raw representation of OpenAPI schema `GroupDMInviteResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GroupDMInviteResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  HasOption* = object ## Lossless raw representation of OpenAPI schema `HasOption`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InnerErrors* = object ## Lossless raw representation of OpenAPI schema `InnerErrors`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  Int53Type* = object ## Lossless raw representation of OpenAPI schema `Int53Type`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  KeywordRuleResponse* = object ## Lossless raw representation of OpenAPI schema `KeywordRuleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/KeywordRuleResponse/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  KeywordTriggerMetadata* = object ## Lossless raw representation of OpenAPI schema `KeywordTriggerMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  KeywordTriggerMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `KeywordTriggerMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  KeywordUpsertRequest* = object ## Lossless raw representation of OpenAPI schema `KeywordUpsertRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/KeywordUpsertRequest/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  KeywordUpsertRequestPartial* = object ## Lossless raw representation of OpenAPI schema `KeywordUpsertRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/KeywordUpsertRequestPartial/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ListApplicationEmojisResponse* = object ## Lossless raw representation of OpenAPI schema `ListApplicationEmojisResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ListGuildSoundboardSoundsResponse* = object ## Lossless raw representation of OpenAPI schema `ListGuildSoundboardSoundsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MLSpamRuleResponse* = object ## Lossless raw representation of OpenAPI schema `MLSpamRuleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MLSpamRuleResponse/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MLSpamTriggerMetadata* = object ## Lossless raw representation of OpenAPI schema `MLSpamTriggerMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MLSpamTriggerMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `MLSpamTriggerMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MLSpamUpsertRequest* = object ## Lossless raw representation of OpenAPI schema `MLSpamUpsertRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MLSpamUpsertRequest/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MLSpamUpsertRequestPartial* = object ## Lossless raw representation of OpenAPI schema `MLSpamUpsertRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MLSpamUpsertRequestPartial/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionSpamRuleResponse* = object ## Lossless raw representation of OpenAPI schema `MentionSpamRuleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionSpamRuleResponse/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionSpamTriggerMetadata* = object ## Lossless raw representation of OpenAPI schema `MentionSpamTriggerMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionSpamTriggerMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `MentionSpamTriggerMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionSpamUpsertRequest* = object ## Lossless raw representation of OpenAPI schema `MentionSpamUpsertRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionSpamUpsertRequest/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionSpamUpsertRequestPartial* = object ## Lossless raw representation of OpenAPI schema `MentionSpamUpsertRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionSpamUpsertRequestPartial/properties/trigger_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionableSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `MentionableSelectComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionableSelectComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/MentionableSelectComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionableSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `MentionableSelectComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionableSelectComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/MentionableSelectComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MentionableSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `MentionableSelectComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MentionableSelectComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MetadataItemTypes* = object ## Lossless raw representation of OpenAPI schema `MetadataItemTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MinimalContentMessageResponse* = object ## Lossless raw representation of OpenAPI schema `MinimalContentMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ModalSubmitInteractionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `ModalSubmitInteractionMetadataResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ModalSubmitInteractionMetadataResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MultipleChoiceFormFieldResponse* = object ## Lossless raw representation of OpenAPI schema `MultipleChoiceFormFieldResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MultipleChoiceFormFieldResponse/properties/field_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MyGuildResponse* = object ## Lossless raw representation of OpenAPI schema `MyGuildResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MyGuildResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  NameplatePalette* = object ## Lossless raw representation of OpenAPI schema `NameplatePalette`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  NewMemberActionResponse* = object ## Lossless raw representation of OpenAPI schema `NewMemberActionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  NewMemberActionType* = object ## Lossless raw representation of OpenAPI schema `NewMemberActionType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OnboardingPromptOptionRequest* = object ## Lossless raw representation of OpenAPI schema `OnboardingPromptOptionRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OnboardingPromptOptionResponse* = object ## Lossless raw representation of OpenAPI schema `OnboardingPromptOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OnboardingPromptResponse* = object ## Lossless raw representation of OpenAPI schema `OnboardingPromptResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OnboardingPromptType* = object ## Lossless raw representation of OpenAPI schema `OnboardingPromptType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ParagraphFormFieldResponse* = object ## Lossless raw representation of OpenAPI schema `ParagraphFormFieldResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ParagraphFormFieldResponse/properties/field_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PartialDiscordIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `PartialDiscordIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PartialDiscordIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PartialExternalConnectionIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `PartialExternalConnectionIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PartialExternalConnectionIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PartialGuildSubscriptionIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `PartialGuildSubscriptionIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PartialGuildSubscriptionIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PinnedMessageResponse* = object ## Lossless raw representation of OpenAPI schema `PinnedMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PinnedMessagesResponse* = object ## Lossless raw representation of OpenAPI schema `PinnedMessagesResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PremiumGuildTiers* = object ## Lossless raw representation of OpenAPI schema `PremiumGuildTiers`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PremiumTypes* = object ## Lossless raw representation of OpenAPI schema `PremiumTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PrivateApplicationResponse* = object ## Lossless raw representation of OpenAPI schema `PrivateApplicationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PrivateApplicationResponse/properties/event_webhooks_types/items/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    ## - `#/components/schemas/PrivateApplicationResponse/properties/flags_new`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PrivateChannelLocation* = object ## Lossless raw representation of OpenAPI schema `PrivateChannelLocation`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PrivateChannelLocation/properties/kind/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PrivateChannelResponse* = object ## Lossless raw representation of OpenAPI schema `PrivateChannelResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PrivateChannelResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PrivateGroupChannelResponse* = object ## Lossless raw representation of OpenAPI schema `PrivateGroupChannelResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PrivateGroupChannelResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PrivateGuildMemberResponse* = object ## Lossless raw representation of OpenAPI schema `PrivateGuildMemberResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/PrivateGuildMemberResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ProvisionalTokenResponse* = object ## Lossless raw representation of OpenAPI schema `ProvisionalTokenResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PruneGuildRequest* = object ## Lossless raw representation of OpenAPI schema `PruneGuildRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PurchaseNotificationResponse* = object ## Lossless raw representation of OpenAPI schema `PurchaseNotificationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PurchaseType* = object ## Lossless raw representation of OpenAPI schema `PurchaseType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  QuarantineUserAction* = object ## Lossless raw representation of OpenAPI schema `QuarantineUserAction`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/QuarantineUserAction/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  QuarantineUserActionMetadata* = object ## Lossless raw representation of OpenAPI schema `QuarantineUserActionMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  QuarantineUserActionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `QuarantineUserActionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  QuarantineUserActionResponse* = object ## Lossless raw representation of OpenAPI schema `QuarantineUserActionResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/QuarantineUserActionResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RatelimitedResponse* = object ## Lossless raw representation of OpenAPI schema `RatelimitedResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ReactionTypes* = object ## Lossless raw representation of OpenAPI schema `ReactionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RecurrenceRule* = object ## Lossless raw representation of OpenAPI schema `RecurrenceRule`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RecurrenceRuleFrequencies* = object ## Lossless raw representation of OpenAPI schema `RecurrenceRuleFrequencies`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RecurrenceRuleMonths* = object ## Lossless raw representation of OpenAPI schema `RecurrenceRuleMonths`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RecurrenceRuleResponse* = object ## Lossless raw representation of OpenAPI schema `RecurrenceRuleResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RecurrenceRuleWeekdays* = object ## Lossless raw representation of OpenAPI schema `RecurrenceRuleWeekdays`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ResolvedObjectsResponse* = object ## Lossless raw representation of OpenAPI schema `ResolvedObjectsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ResourceChannelResponse* = object ## Lossless raw representation of OpenAPI schema `ResourceChannelResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbed* = object ## Lossless raw representation of OpenAPI schema `RichEmbed`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedAuthor* = object ## Lossless raw representation of OpenAPI schema `RichEmbedAuthor`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedField* = object ## Lossless raw representation of OpenAPI schema `RichEmbedField`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedFooter* = object ## Lossless raw representation of OpenAPI schema `RichEmbedFooter`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedImage* = object ## Lossless raw representation of OpenAPI schema `RichEmbedImage`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedProvider* = object ## Lossless raw representation of OpenAPI schema `RichEmbedProvider`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedThumbnail* = object ## Lossless raw representation of OpenAPI schema `RichEmbedThumbnail`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RichEmbedVideo* = object ## Lossless raw representation of OpenAPI schema `RichEmbedVideo`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SDKMessageRequest* = object ## Lossless raw representation of OpenAPI schema `SDKMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SKUIneligibilityReason* = object ## Lossless raw representation of OpenAPI schema `SKUIneligibilityReason`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ScheduledEventResponse* = object ## Lossless raw representation of OpenAPI schema `ScheduledEventResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ScheduledEventUserCountResponse* = object ## Lossless raw representation of OpenAPI schema `ScheduledEventUserCountResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ScheduledEventUserResponse* = object ## Lossless raw representation of OpenAPI schema `ScheduledEventUserResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SearchIndexNotReadyResponse* = object ## Lossless raw representation of OpenAPI schema `SearchIndexNotReadyResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SearchMessageResponse* = object ## Lossless raw representation of OpenAPI schema `SearchMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SearchableEmbedType* = object ## Lossless raw representation of OpenAPI schema `SearchableEmbedType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SettingsEmojiResponse* = object ## Lossless raw representation of OpenAPI schema `SettingsEmojiResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SlackWebhook* = object ## Lossless raw representation of OpenAPI schema `SlackWebhook`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SnowflakeSelectDefaultValueTypes* = object ## Lossless raw representation of OpenAPI schema `SnowflakeSelectDefaultValueTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SnowflakeType* = object ## Lossless raw representation of OpenAPI schema `SnowflakeType`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/SnowflakeType`
    ##   uses `snowflake` with `decimal-string-at-json-boundary`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SocialLayerSKUPurchaseEligibilityCallbackData* = object ## Lossless raw representation of OpenAPI schema `SocialLayerSKUPurchaseEligibilityCallbackData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SortingMode* = object ## Lossless raw representation of OpenAPI schema `SortingMode`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SortingOrder* = object ## Lossless raw representation of OpenAPI schema `SortingOrder`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StandardStickerResponse* = object ## Lossless raw representation of OpenAPI schema `StandardStickerResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/StandardStickerResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StringSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `StringSelectComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/StringSelectComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/StringSelectComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StringSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `StringSelectComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/StringSelectComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/StringSelectComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StringSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `StringSelectComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/StringSelectComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StringSelectOptionForRequest* = object ## Lossless raw representation of OpenAPI schema `StringSelectOptionForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StringSelectOptionResponse* = object ## Lossless raw representation of OpenAPI schema `StringSelectOptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TargetUsersJobStatusResponse* = object ## Lossless raw representation of OpenAPI schema `TargetUsersJobStatusResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TargetUsersJobStatusTypes* = object ## Lossless raw representation of OpenAPI schema `TargetUsersJobStatusTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TeamMemberResponse* = object ## Lossless raw representation of OpenAPI schema `TeamMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TeamMemberRoles* = object ## Lossless raw representation of OpenAPI schema `TeamMemberRoles`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TeamMembershipStates* = object ## Lossless raw representation of OpenAPI schema `TeamMembershipStates`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TeamResponse* = object ## Lossless raw representation of OpenAPI schema `TeamResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TermsFormFieldResponse* = object ## Lossless raw representation of OpenAPI schema `TermsFormFieldResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TermsFormFieldResponse/properties/field_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextInputComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `TextInputComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextInputComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/TextInputComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextInputComponentResponse* = object ## Lossless raw representation of OpenAPI schema `TextInputComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextInputComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextInputFormFieldResponse* = object ## Lossless raw representation of OpenAPI schema `TextInputFormFieldResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextInputFormFieldResponse/properties/field_type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextInputStyleTypes* = object ## Lossless raw representation of OpenAPI schema `TextInputStyleTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TypingIndicatorResponse* = object ## Lossless raw representation of OpenAPI schema `TypingIndicatorResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UInt32Type* = object ## Lossless raw representation of OpenAPI schema `UInt32Type`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UnbanUserFromGuildRequest* = object ## Lossless raw representation of OpenAPI schema `UnbanUserFromGuildRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UnfurledMediaRequest* = object ## Lossless raw representation of OpenAPI schema `UnfurledMediaRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UnfurledMediaRequestWithAttachmentReferenceRequired* = object ## Lossless raw representation of OpenAPI schema `UnfurledMediaRequestWithAttachmentReferenceRequired`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UnfurledMediaResponse* = object ## Lossless raw representation of OpenAPI schema `UnfurledMediaResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateApplicationUserRoleConnectionRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateApplicationUserRoleConnectionRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateDMRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateDMRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateDefaultReactionEmojiRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateDefaultReactionEmojiRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateGroupDMRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateGroupDMRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateGuildChannelRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateGuildChannelRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/UpdateGuildChannelRequestPartial/properties/type/oneOf/1/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateGuildOnboardingRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateGuildOnboardingRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateOnboardingPromptRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateOnboardingPromptRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateRolePositionsRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateRolePositionsRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateRoleRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateRoleRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/UpdateRoleRequestPartial/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateSelfVoiceStateRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateSelfVoiceStateRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateThreadRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateThreadRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateThreadTagRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateThreadTagRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateVoiceStateRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UpdateVoiceStateRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VanityURLErrorResponse* = object ## Lossless raw representation of OpenAPI schema `VanityURLErrorResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VanityURLResponse* = object ## Lossless raw representation of OpenAPI schema `VanityURLResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VerificationLevels* = object ## Lossless raw representation of OpenAPI schema `VerificationLevels`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VideoQualityModes* = object ## Lossless raw representation of OpenAPI schema `VideoQualityModes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WelcomeMessageResponse* = object ## Lossless raw representation of OpenAPI schema `WelcomeMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
