## Lossless raw Discord models in the `component` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ActionRowComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ActionRowComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/ActionRowComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActionRowComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ActionRowComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/ActionRowComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActionRowComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ActionRowComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ButtonComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ButtonComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/ButtonComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ButtonComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ButtonComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonStyleTypes* = object ## Lossless raw representation of OpenAPI schema `ButtonStyleTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CheckboxComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/CheckboxComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxGroupComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxGroupComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/CheckboxGroupComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/CheckboxGroupComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxGroupOptionForRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxGroupOptionForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ComponentEmojiForRequest* = object ## Lossless raw representation of OpenAPI schema `ComponentEmojiForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ComponentEmojiResponse* = object ## Lossless raw representation of OpenAPI schema `ComponentEmojiResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ContainerComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ContainerComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ContainerComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/ContainerComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ContainerComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ContainerComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ContainerComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FileComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `FileComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FileComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/FileComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FileComponentResponse* = object ## Lossless raw representation of OpenAPI schema `FileComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/FileComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LabelComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `LabelComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/LabelComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/LabelComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MediaGalleryComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/MediaGalleryComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryComponentResponse* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/MediaGalleryComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryItemRequest* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryItemRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryItemResponse* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryItemResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RadioGroupComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `RadioGroupComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RadioGroupComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/RadioGroupComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RadioGroupOptionForRequest* = object ## Lossless raw representation of OpenAPI schema `RadioGroupOptionForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SectionComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `SectionComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/SectionComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/SectionComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SectionComponentResponse* = object ## Lossless raw representation of OpenAPI schema `SectionComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/SectionComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SeparatorComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `SeparatorComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/SeparatorComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/SeparatorComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SeparatorComponentResponse* = object ## Lossless raw representation of OpenAPI schema `SeparatorComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/SeparatorComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextDisplayComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/TextDisplayComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextDisplayComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/TextDisplayComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentResponse* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/TextDisplayComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThumbnailComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ThumbnailComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ThumbnailComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/ThumbnailComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThumbnailComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ThumbnailComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/ThumbnailComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
