## Lossless raw Discord models in the `component` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  ActionRowComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActionRowComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ActionRowComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ActionRowComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ButtonComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ButtonComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ButtonStyleTypes* = object ## Lossless raw representation of OpenAPI schema `ButtonStyleTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxGroupComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxGroupComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CheckboxGroupOptionForRequest* = object ## Lossless raw representation of OpenAPI schema `CheckboxGroupOptionForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ComponentEmojiForRequest* = object ## Lossless raw representation of OpenAPI schema `ComponentEmojiForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ComponentEmojiResponse* = object ## Lossless raw representation of OpenAPI schema `ComponentEmojiResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ContainerComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ContainerComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ContainerComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ContainerComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FileComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `FileComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  FileComponentResponse* = object ## Lossless raw representation of OpenAPI schema `FileComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LabelComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `LabelComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryComponentResponse* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryItemRequest* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryItemRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MediaGalleryItemResponse* = object ## Lossless raw representation of OpenAPI schema `MediaGalleryItemResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RadioGroupComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `RadioGroupComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RadioGroupOptionForRequest* = object ## Lossless raw representation of OpenAPI schema `RadioGroupOptionForRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SectionComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `SectionComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SectionComponentResponse* = object ## Lossless raw representation of OpenAPI schema `SectionComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SeparatorComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `SeparatorComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SeparatorComponentResponse* = object ## Lossless raw representation of OpenAPI schema `SeparatorComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  TextDisplayComponentResponse* = object ## Lossless raw representation of OpenAPI schema `TextDisplayComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThumbnailComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `ThumbnailComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ThumbnailComponentResponse* = object ## Lossless raw representation of OpenAPI schema `ThumbnailComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
