## Lossless raw Discord models in the `guild` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  BanUserFromGuildRequest* = object ## Lossless raw representation of OpenAPI schema `BanUserFromGuildRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildAuditLogResponse* = object ## Lossless raw representation of OpenAPI schema `GuildAuditLogResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildBanResponse* = object ## Lossless raw representation of OpenAPI schema `GuildBanResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildChannelLocation* = object ## Lossless raw representation of OpenAPI schema `GuildChannelLocation`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildChannelLocation/properties/kind/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildChannelResponse* = object ## Lossless raw representation of OpenAPI schema `GuildChannelResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildChannelResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    ## - `#/components/schemas/GuildChannelResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildExplicitContentFilterTypes* = object ## Lossless raw representation of OpenAPI schema `GuildExplicitContentFilterTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildFeatures* = object ## Lossless raw representation of OpenAPI schema `GuildFeatures`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildHomeSettingsResponse* = object ## Lossless raw representation of OpenAPI schema `GuildHomeSettingsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildIncidentActionsRequest* = object ## Lossless raw representation of OpenAPI schema `GuildIncidentActionsRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildIncidentsDataResponse* = object ## Lossless raw representation of OpenAPI schema `GuildIncidentsDataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildIncomingWebhookResponse* = object ## Lossless raw representation of OpenAPI schema `GuildIncomingWebhookResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildIncomingWebhookResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildInviteResponse* = object ## Lossless raw representation of OpenAPI schema `GuildInviteResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildInviteResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildJoinRequestApplicationStatus* = object ## Lossless raw representation of OpenAPI schema `GuildJoinRequestApplicationStatus`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildJoinRequestResponse* = object ## Lossless raw representation of OpenAPI schema `GuildJoinRequestResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildJoinRequestsListResponse* = object ## Lossless raw representation of OpenAPI schema `GuildJoinRequestsListResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildLivelinessResponse* = object ## Lossless raw representation of OpenAPI schema `GuildLivelinessResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildMFALevel* = object ## Lossless raw representation of OpenAPI schema `GuildMFALevel`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildMemberResponse* = object ## Lossless raw representation of OpenAPI schema `GuildMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildMemberVerificationFormFieldType* = object ## Lossless raw representation of OpenAPI schema `GuildMemberVerificationFormFieldType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildNSFWContentLevel* = object ## Lossless raw representation of OpenAPI schema `GuildNSFWContentLevel`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildOnboardingMode* = object ## Lossless raw representation of OpenAPI schema `GuildOnboardingMode`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildOnboardingResponse* = object ## Lossless raw representation of OpenAPI schema `GuildOnboardingResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `GuildPatchRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildPatchRequestPartial`
    ##   uses `patch-object` with `unset-null-value`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildPreviewResponse* = object ## Lossless raw representation of OpenAPI schema `GuildPreviewResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildProductPurchaseResponse* = object ## Lossless raw representation of OpenAPI schema `GuildProductPurchaseResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildPruneResponse* = object ## Lossless raw representation of OpenAPI schema `GuildPruneResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildResponse* = object ## Lossless raw representation of OpenAPI schema `GuildResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildRoleColorsResponse* = object ## Lossless raw representation of OpenAPI schema `GuildRoleColorsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildRoleResponse* = object ## Lossless raw representation of OpenAPI schema `GuildRoleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildRoleResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildRoleTagsResponse* = object ## Lossless raw representation of OpenAPI schema `GuildRoleTagsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventEntityTypes* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventEntityTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventExceptionCreateRequest* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventExceptionCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventExceptionPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventExceptionPatchRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildScheduledEventExceptionPatchRequestPartial`
    ##   uses `patch-object` with `unset-null-value`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventExceptionResponse* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventExceptionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventPrivacyLevels* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventPrivacyLevels`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventStatuses* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventStatuses`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildScheduledEventUserResponses* = object ## Lossless raw representation of OpenAPI schema `GuildScheduledEventUserResponses`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildSearchResponse* = object ## Lossless raw representation of OpenAPI schema `GuildSearchResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildStickerResponse* = object ## Lossless raw representation of OpenAPI schema `GuildStickerResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildStickerResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildSubscriptionIntegrationResponse* = object ## Lossless raw representation of OpenAPI schema `GuildSubscriptionIntegrationResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildSubscriptionIntegrationResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateChannelResponse* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateChannelResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildTemplateChannelResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateChannelTags* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateChannelTags`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateResponse* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateRoleColorsResponse* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateRoleColorsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateRoleResponse* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateRoleResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/GuildTemplateRoleResponse/properties/permissions`
    ##   uses `extensible-bits` with `decimal-string-arbitrary-width`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildTemplateSnapshotResponse* = object ## Lossless raw representation of OpenAPI schema `GuildTemplateSnapshotResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildWelcomeChannel* = object ## Lossless raw representation of OpenAPI schema `GuildWelcomeChannel`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildWelcomeScreenChannelResponse* = object ## Lossless raw representation of OpenAPI schema `GuildWelcomeScreenChannelResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildWelcomeScreenResponse* = object ## Lossless raw representation of OpenAPI schema `GuildWelcomeScreenResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  GuildWithCountsResponse* = object ## Lossless raw representation of OpenAPI schema `GuildWithCountsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleColors* = object ## Lossless raw representation of OpenAPI schema `RoleColors`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `RoleSelectComponentForMessageRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RoleSelectComponentForMessageRequest`
    ##   uses `legal-component-tree` with `validated-parent-child-tree-max-40`.
    ## - `#/components/schemas/RoleSelectComponentForMessageRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `RoleSelectComponentForModalRequest`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RoleSelectComponentForModalRequest`
    ##   uses `modal-label-tree` with `typed-form-schema-and-decoder`.
    ## - `#/components/schemas/RoleSelectComponentForModalRequest/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `RoleSelectComponentResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RoleSelectComponentResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleSelectDefaultValue* = object ## Lossless raw representation of OpenAPI schema `RoleSelectDefaultValue`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RoleSelectDefaultValue/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  RoleSelectDefaultValueResponse* = object ## Lossless raw representation of OpenAPI schema `RoleSelectDefaultValueResponse`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/RoleSelectDefaultValueResponse/properties/type/enum`
    ##   uses `open-enum` with `raw-value-plus-known-view`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WelcomeScreenPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `WelcomeScreenPatchRequestPartial`.
    ##
    ## Applied semantic overlay metadata:
    ## - `#/components/schemas/WelcomeScreenPatchRequestPartial`
    ##   uses `patch-object` with `unset-null-value`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetActivity* = object ## Lossless raw representation of OpenAPI schema `WidgetActivity`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetChannel* = object ## Lossless raw representation of OpenAPI schema `WidgetChannel`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetImageStyles* = object ## Lossless raw representation of OpenAPI schema `WidgetImageStyles`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetMember* = object ## Lossless raw representation of OpenAPI schema `WidgetMember`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetResponse* = object ## Lossless raw representation of OpenAPI schema `WidgetResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetSettingsResponse* = object ## Lossless raw representation of OpenAPI schema `WidgetSettingsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WidgetUserDiscriminator* = object ## Lossless raw representation of OpenAPI schema `WidgetUserDiscriminator`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
