## Lossless raw Discord models in the `interaction` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  CreateMessageInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `CreateMessageInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  CreateMessageInteractionCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `CreateMessageInteractionCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IncomingWebhookUpdateForInteractionCallbackRequestPartial* = object ## Lossless raw representation of OpenAPI schema `IncomingWebhookUpdateForInteractionCallbackRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionApplicationCommandAutocompleteCallbackIntegerData* = object ## Lossless raw representation of OpenAPI schema `InteractionApplicationCommandAutocompleteCallbackIntegerData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionApplicationCommandAutocompleteCallbackNumberData* = object ## Lossless raw representation of OpenAPI schema `InteractionApplicationCommandAutocompleteCallbackNumberData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionApplicationCommandAutocompleteCallbackStringData* = object ## Lossless raw representation of OpenAPI schema `InteractionApplicationCommandAutocompleteCallbackStringData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `InteractionCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionCallbackTypes* = object ## Lossless raw representation of OpenAPI schema `InteractionCallbackTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionContextType* = object ## Lossless raw representation of OpenAPI schema `InteractionContextType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionResponse* = object ## Lossless raw representation of OpenAPI schema `InteractionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InteractionTypes* = object ## Lossless raw representation of OpenAPI schema `InteractionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LaunchActivityInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `LaunchActivityInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LaunchActivityInteractionCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `LaunchActivityInteractionCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ModalInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `ModalInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  ModalInteractionCallbackRequestData* = object ## Lossless raw representation of OpenAPI schema `ModalInteractionCallbackRequestData`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PongInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `PongInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  SocialLayerSKUPurchaseEligibilityInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `SocialLayerSKUPurchaseEligibilityInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateMessageInteractionCallbackRequest* = object ## Lossless raw representation of OpenAPI schema `UpdateMessageInteractionCallbackRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UpdateMessageInteractionCallbackResponse* = object ## Lossless raw representation of OpenAPI schema `UpdateMessageInteractionCallbackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
