## Lossless raw Discord models in the `integration` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  IntegrationApplicationResponse* = object ## Lossless raw representation of OpenAPI schema `IntegrationApplicationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IntegrationExpireBehaviorTypes* = object ## Lossless raw representation of OpenAPI schema `IntegrationExpireBehaviorTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IntegrationExpireGracePeriodTypes* = object ## Lossless raw representation of OpenAPI schema `IntegrationExpireGracePeriodTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IntegrationTypes* = object ## Lossless raw representation of OpenAPI schema `IntegrationTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
