## Lossless raw Discord models in the `invite` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  InviteApplicationResponse* = object ## Lossless raw representation of OpenAPI schema `InviteApplicationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteChannelRecipientResponse* = object ## Lossless raw representation of OpenAPI schema `InviteChannelRecipientResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteChannelResponse* = object ## Lossless raw representation of OpenAPI schema `InviteChannelResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteGuildResponse* = object ## Lossless raw representation of OpenAPI schema `InviteGuildResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteGuildRoleResponse* = object ## Lossless raw representation of OpenAPI schema `InviteGuildRoleResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteTargetTypes* = object ## Lossless raw representation of OpenAPI schema `InviteTargetTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  InviteTypes* = object ## Lossless raw representation of OpenAPI schema `InviteTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
