## Lossless raw Discord models in the `lobby` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  LobbyGuildInviteResponse* = object ## Lossless raw representation of OpenAPI schema `LobbyGuildInviteResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LobbyMemberRequest* = object ## Lossless raw representation of OpenAPI schema `LobbyMemberRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LobbyMemberResponse* = object ## Lossless raw representation of OpenAPI schema `LobbyMemberResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LobbyMessageResponse* = object ## Lossless raw representation of OpenAPI schema `LobbyMessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  LobbyResponse* = object ## Lossless raw representation of OpenAPI schema `LobbyResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
