## Lossless raw Discord models in the `message` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  AllowedMentionTypes* = object ## Lossless raw representation of OpenAPI schema `AllowedMentionTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  AttachmentResponse* = object ## Lossless raw representation of OpenAPI schema `AttachmentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EmbeddedActivityInstance* = object ## Lossless raw representation of OpenAPI schema `EmbeddedActivityInstance`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  EmbeddedActivityLocationKind* = object ## Lossless raw representation of OpenAPI schema `EmbeddedActivityLocationKind`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageActivityResponse* = object ## Lossless raw representation of OpenAPI schema `MessageActivityResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageAllowedMentionsRequest* = object ## Lossless raw representation of OpenAPI schema `MessageAllowedMentionsRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageAttachmentRequest* = object ## Lossless raw representation of OpenAPI schema `MessageAttachmentRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageAttachmentResponse* = object ## Lossless raw representation of OpenAPI schema `MessageAttachmentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageCallResponse* = object ## Lossless raw representation of OpenAPI schema `MessageCallResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageComponentInteractionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `MessageComponentInteractionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageComponentSeparatorSpacingSize* = object ## Lossless raw representation of OpenAPI schema `MessageComponentSeparatorSpacingSize`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageComponentTypes* = object ## Lossless raw representation of OpenAPI schema `MessageComponentTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageCreateRequest* = object ## Lossless raw representation of OpenAPI schema `MessageCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEditRequestPartial* = object ## Lossless raw representation of OpenAPI schema `MessageEditRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedAuthorResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedAuthorResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedFieldResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedFieldResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedFooterResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedFooterResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedImageResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedImageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedProviderResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedProviderResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageEmbedVideoResponse* = object ## Lossless raw representation of OpenAPI schema `MessageEmbedVideoResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageInteractionResponse* = object ## Lossless raw representation of OpenAPI schema `MessageInteractionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageMentionChannelResponse* = object ## Lossless raw representation of OpenAPI schema `MessageMentionChannelResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReactionCountDetailsResponse* = object ## Lossless raw representation of OpenAPI schema `MessageReactionCountDetailsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReactionEmojiResponse* = object ## Lossless raw representation of OpenAPI schema `MessageReactionEmojiResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReactionResponse* = object ## Lossless raw representation of OpenAPI schema `MessageReactionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReferenceRequest* = object ## Lossless raw representation of OpenAPI schema `MessageReferenceRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReferenceResponse* = object ## Lossless raw representation of OpenAPI schema `MessageReferenceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageReferenceType* = object ## Lossless raw representation of OpenAPI schema `MessageReferenceType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageResponse* = object ## Lossless raw representation of OpenAPI schema `MessageResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageRoleSubscriptionDataResponse* = object ## Lossless raw representation of OpenAPI schema `MessageRoleSubscriptionDataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageShareCustomUserThemeBaseTheme* = object ## Lossless raw representation of OpenAPI schema `MessageShareCustomUserThemeBaseTheme`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageSnapshotResponse* = object ## Lossless raw representation of OpenAPI schema `MessageSnapshotResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageStickerItemResponse* = object ## Lossless raw representation of OpenAPI schema `MessageStickerItemResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  MessageType* = object ## Lossless raw representation of OpenAPI schema `MessageType`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
