## Lossless raw Discord models in the `oauth2` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  OAuth2GetAuthorizationResponse* = object ## Lossless raw representation of OpenAPI schema `OAuth2GetAuthorizationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OAuth2GetKeys* = object ## Lossless raw representation of OpenAPI schema `OAuth2GetKeys`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OAuth2GetOpenIDConnectUserInfoResponse* = object ## Lossless raw representation of OpenAPI schema `OAuth2GetOpenIDConnectUserInfoResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OAuth2Key* = object ## Lossless raw representation of OpenAPI schema `OAuth2Key`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  OAuth2Scopes* = object ## Lossless raw representation of OpenAPI schema `OAuth2Scopes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
