## Lossless raw Discord models in the `poll` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  PollAnswerCreateRequest* = object ## Lossless raw representation of OpenAPI schema `PollAnswerCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollAnswerDetailsResponse* = object ## Lossless raw representation of OpenAPI schema `PollAnswerDetailsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollAnswerResponse* = object ## Lossless raw representation of OpenAPI schema `PollAnswerResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollCreateRequest* = object ## Lossless raw representation of OpenAPI schema `PollCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollEmoji* = object ## Lossless raw representation of OpenAPI schema `PollEmoji`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollEmojiCreateRequest* = object ## Lossless raw representation of OpenAPI schema `PollEmojiCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollLayoutTypes* = object ## Lossless raw representation of OpenAPI schema `PollLayoutTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollMedia* = object ## Lossless raw representation of OpenAPI schema `PollMedia`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollMediaCreateRequest* = object ## Lossless raw representation of OpenAPI schema `PollMediaCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollMediaResponse* = object ## Lossless raw representation of OpenAPI schema `PollMediaResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollResponse* = object ## Lossless raw representation of OpenAPI schema `PollResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollResultsEntryResponse* = object ## Lossless raw representation of OpenAPI schema `PollResultsEntryResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  PollResultsResponse* = object ## Lossless raw representation of OpenAPI schema `PollResultsResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
