## Lossless raw Discord models in the `stage_instance` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  StageInstanceResponse* = object ## Lossless raw representation of OpenAPI schema `StageInstanceResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StageInstancesPrivacyLevels* = object ## Lossless raw representation of OpenAPI schema `StageInstancesPrivacyLevels`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StageScheduledEventCreateRequest* = object ## Lossless raw representation of OpenAPI schema `StageScheduledEventCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StageScheduledEventPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `StageScheduledEventPatchRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StageScheduledEventResponse* = object ## Lossless raw representation of OpenAPI schema `StageScheduledEventResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
