## Lossless raw Discord models in the `sticker` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  StickerFormatTypes* = object ## Lossless raw representation of OpenAPI schema `StickerFormatTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StickerPackCollectionResponse* = object ## Lossless raw representation of OpenAPI schema `StickerPackCollectionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StickerPackResponse* = object ## Lossless raw representation of OpenAPI schema `StickerPackResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  StickerTypes* = object ## Lossless raw representation of OpenAPI schema `StickerTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
