## Lossless raw Discord models in the `user` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  AccountResponse* = object ## Lossless raw representation of OpenAPI schema `AccountResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserAvatarDecorationResponse* = object ## Lossless raw representation of OpenAPI schema `UserAvatarDecorationResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserCollectiblesResponse* = object ## Lossless raw representation of OpenAPI schema `UserCollectiblesResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserCommunicationDisabledAction* = object ## Lossless raw representation of OpenAPI schema `UserCommunicationDisabledAction`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserCommunicationDisabledActionMetadata* = object ## Lossless raw representation of OpenAPI schema `UserCommunicationDisabledActionMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserCommunicationDisabledActionMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `UserCommunicationDisabledActionMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserCommunicationDisabledActionResponse* = object ## Lossless raw representation of OpenAPI schema `UserCommunicationDisabledActionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserGuildOnboardingResponse* = object ## Lossless raw representation of OpenAPI schema `UserGuildOnboardingResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserNameplateResponse* = object ## Lossless raw representation of OpenAPI schema `UserNameplateResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserNotificationSettings* = object ## Lossless raw representation of OpenAPI schema `UserNotificationSettings`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserPIIResponse* = object ## Lossless raw representation of OpenAPI schema `UserPIIResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserPrimaryGuildResponse* = object ## Lossless raw representation of OpenAPI schema `UserPrimaryGuildResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserProfileMetadata* = object ## Lossless raw representation of OpenAPI schema `UserProfileMetadata`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserProfileMetadataResponse* = object ## Lossless raw representation of OpenAPI schema `UserProfileMetadataResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserProfileRuleResponse* = object ## Lossless raw representation of OpenAPI schema `UserProfileRuleResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserProfileUpsertRequest* = object ## Lossless raw representation of OpenAPI schema `UserProfileUpsertRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserProfileUpsertRequestPartial* = object ## Lossless raw representation of OpenAPI schema `UserProfileUpsertRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserResponse* = object ## Lossless raw representation of OpenAPI schema `UserResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserSelectComponentForMessageRequest* = object ## Lossless raw representation of OpenAPI schema `UserSelectComponentForMessageRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserSelectComponentForModalRequest* = object ## Lossless raw representation of OpenAPI schema `UserSelectComponentForModalRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserSelectComponentResponse* = object ## Lossless raw representation of OpenAPI schema `UserSelectComponentResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserSelectDefaultValue* = object ## Lossless raw representation of OpenAPI schema `UserSelectDefaultValue`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  UserSelectDefaultValueResponse* = object ## Lossless raw representation of OpenAPI schema `UserSelectDefaultValueResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
