## Lossless raw Discord models in the `voice` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  VoiceRegionResponse* = object ## Lossless raw representation of OpenAPI schema `VoiceRegionResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VoiceScheduledEventCreateRequest* = object ## Lossless raw representation of OpenAPI schema `VoiceScheduledEventCreateRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VoiceScheduledEventPatchRequestPartial* = object ## Lossless raw representation of OpenAPI schema `VoiceScheduledEventPatchRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VoiceScheduledEventResponse* = object ## Lossless raw representation of OpenAPI schema `VoiceScheduledEventResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  VoiceStateResponse* = object ## Lossless raw representation of OpenAPI schema `VoiceStateResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
