## Lossless raw Discord models in the `webhook` schema group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import std/json

type
  IncomingWebhookInteractionRequest* = object ## Lossless raw representation of OpenAPI schema `IncomingWebhookInteractionRequest`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IncomingWebhookRequestPartial* = object ## Lossless raw representation of OpenAPI schema `IncomingWebhookRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  IncomingWebhookUpdateRequestPartial* = object ## Lossless raw representation of OpenAPI schema `IncomingWebhookUpdateRequestPartial`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WebhookSlackEmbed* = object ## Lossless raw representation of OpenAPI schema `WebhookSlackEmbed`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WebhookSlackEmbedField* = object ## Lossless raw representation of OpenAPI schema `WebhookSlackEmbedField`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WebhookSourceChannelResponse* = object ## Lossless raw representation of OpenAPI schema `WebhookSourceChannelResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WebhookSourceGuildResponse* = object ## Lossless raw representation of OpenAPI schema `WebhookSourceGuildResponse`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.

  WebhookTypes* = object ## Lossless raw representation of OpenAPI schema `WebhookTypes`.
    raw*: JsonNode ## Complete JSON payload, including fields unknown to this schema revision.
