## Stable raw Discord HTTP routes in the `applications` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getMyApplication* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/@me",
    operationId: "get_my_application",
    requestSchema: "",
    responseSchema: "PrivateApplicationResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/@me` (`get_my_application`).
  updateMyApplication* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/applications/@me",
    operationId: "update_my_application",
    requestSchema: "ApplicationFormPartial",
    responseSchema: "PrivateApplicationResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /applications/@me` (`update_my_application`).
  getApplication* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}",
    operationId: "get_application",
    requestSchema: "",
    responseSchema: "PrivateApplicationResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}` (`get_application`).
  updateApplication* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/applications/{application_id}",
    operationId: "update_application",
    requestSchema: "ApplicationFormPartial",
    responseSchema: "PrivateApplicationResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /applications/{application_id}` (`update_application`).
  applicationsGetActivityInstance* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/activity-instances/{instance_id}",
    operationId: "applications_get_activity_instance",
    requestSchema: "",
    responseSchema: "EmbeddedActivityInstance",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/activity-instances/{instance_id}` (`applications_get_activity_instance`).
  uploadApplicationAttachment* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/attachment",
    operationId: "upload_application_attachment",
    requestSchema: "object",
    responseSchema: "ActivitiesAttachmentResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/attachment` (`upload_application_attachment`).
  listApplicationCommands* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/commands",
    operationId: "list_application_commands",
    requestSchema: "",
    responseSchema: "seq[ApplicationCommandResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/commands` (`list_application_commands`).
  createApplicationCommand* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/commands",
    operationId: "create_application_command",
    requestSchema: "ApplicationCommandCreateRequest",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/commands` (`create_application_command`).
  bulkSetApplicationCommands* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/applications/{application_id}/commands",
    operationId: "bulk_set_application_commands",
    requestSchema: "seq[ApplicationCommandUpdateRequest] | null",
    responseSchema: "seq[ApplicationCommandResponse] | null",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /applications/{application_id}/commands` (`bulk_set_application_commands`).
  getApplicationCommand* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/commands/{command_id}",
    operationId: "get_application_command",
    requestSchema: "",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/commands/{command_id}` (`get_application_command`).
  updateApplicationCommand* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/applications/{application_id}/commands/{command_id}",
    operationId: "update_application_command",
    requestSchema: "ApplicationCommandPatchRequestPartial",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /applications/{application_id}/commands/{command_id}` (`update_application_command`).
  deleteApplicationCommand* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/applications/{application_id}/commands/{command_id}",
    operationId: "delete_application_command",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /applications/{application_id}/commands/{command_id}` (`delete_application_command`).
  listApplicationEmojis* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/emojis",
    operationId: "list_application_emojis",
    requestSchema: "",
    responseSchema: "ListApplicationEmojisResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/emojis` (`list_application_emojis`).
  createApplicationEmoji* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/emojis",
    operationId: "create_application_emoji",
    requestSchema: "object",
    responseSchema: "EmojiResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/emojis` (`create_application_emoji`).
  getApplicationEmoji* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/emojis/{emoji_id}",
    operationId: "get_application_emoji",
    requestSchema: "",
    responseSchema: "EmojiResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/emojis/{emoji_id}` (`get_application_emoji`).
  updateApplicationEmoji* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/applications/{application_id}/emojis/{emoji_id}",
    operationId: "update_application_emoji",
    requestSchema: "object",
    responseSchema: "EmojiResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /applications/{application_id}/emojis/{emoji_id}` (`update_application_emoji`).
  deleteApplicationEmoji* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/applications/{application_id}/emojis/{emoji_id}",
    operationId: "delete_application_emoji",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /applications/{application_id}/emojis/{emoji_id}` (`delete_application_emoji`).
  getEntitlements* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/entitlements",
    operationId: "get_entitlements",
    requestSchema: "",
    responseSchema: "seq[EntitlementResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/entitlements` (`get_entitlements`).
  createEntitlement* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/entitlements",
    operationId: "create_entitlement",
    requestSchema: "CreateEntitlementRequestData",
    responseSchema: "EntitlementResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/entitlements` (`create_entitlement`).
  getEntitlement* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/entitlements/{entitlement_id}",
    operationId: "get_entitlement",
    requestSchema: "",
    responseSchema: "EntitlementResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/entitlements/{entitlement_id}` (`get_entitlement`).
  deleteEntitlement* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/applications/{application_id}/entitlements/{entitlement_id}",
    operationId: "delete_entitlement",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /applications/{application_id}/entitlements/{entitlement_id}` (`delete_entitlement`).
  consumeEntitlement* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/entitlements/{entitlement_id}/consume",
    operationId: "consume_entitlement",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/entitlements/{entitlement_id}/consume` (`consume_entitlement`).
  listGuildApplicationCommands* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands",
    operationId: "list_guild_application_commands",
    requestSchema: "",
    responseSchema: "seq[ApplicationCommandResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/guilds/{guild_id}/commands` (`list_guild_application_commands`).
  createGuildApplicationCommand* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands",
    operationId: "create_guild_application_command",
    requestSchema: "ApplicationCommandCreateRequest",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /applications/{application_id}/guilds/{guild_id}/commands` (`create_guild_application_command`).
  bulkSetGuildApplicationCommands* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands",
    operationId: "bulk_set_guild_application_commands",
    requestSchema: "seq[ApplicationCommandUpdateRequest] | null",
    responseSchema: "seq[ApplicationCommandResponse] | null",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /applications/{application_id}/guilds/{guild_id}/commands` (`bulk_set_guild_application_commands`).
  listGuildApplicationCommandPermissions* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/permissions",
    operationId: "list_guild_application_command_permissions",
    requestSchema: "",
    responseSchema: "seq[CommandPermissionsResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/guilds/{guild_id}/commands/permissions` (`list_guild_application_command_permissions`).
  getGuildApplicationCommand* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
    operationId: "get_guild_application_command",
    requestSchema: "",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}` (`get_guild_application_command`).
  updateGuildApplicationCommand* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
    operationId: "update_guild_application_command",
    requestSchema: "ApplicationCommandPatchRequestPartial",
    responseSchema: "ApplicationCommandResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /applications/{application_id}/guilds/{guild_id}/commands/{command_id}` (`update_guild_application_command`).
  deleteGuildApplicationCommand* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
    operationId: "delete_guild_application_command",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /applications/{application_id}/guilds/{guild_id}/commands/{command_id}` (`delete_guild_application_command`).
  getGuildApplicationCommandPermissions* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
    operationId: "get_guild_application_command_permissions",
    requestSchema: "",
    responseSchema: "CommandPermissionsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions` (`get_guild_application_command_permissions`).
  setGuildApplicationCommandPermissions* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
    operationId: "set_guild_application_command_permissions",
    requestSchema: "object",
    responseSchema: "CommandPermissionsResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions` (`set_guild_application_command_permissions`).
  getApplicationRoleConnectionsMetadata* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/applications/{application_id}/role-connections/metadata",
    operationId: "get_application_role_connections_metadata",
    requestSchema: "",
    responseSchema: "seq[ApplicationRoleConnectionsMetadataItemResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /applications/{application_id}/role-connections/metadata` (`get_application_role_connections_metadata`).
  updateApplicationRoleConnectionsMetadata* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/applications/{application_id}/role-connections/metadata",
    operationId: "update_application_role_connections_metadata",
    requestSchema: "seq[ApplicationRoleConnectionsMetadataItemRequest] | null",
    responseSchema: "seq[ApplicationRoleConnectionsMetadataItemResponse] | null",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /applications/{application_id}/role-connections/metadata` (`update_application_role_connections_metadata`).
  applicationsRoutes*: array[33, RawRoute] = [
    getMyApplication,
    updateMyApplication,
    getApplication,
    updateApplication,
    applicationsGetActivityInstance,
    uploadApplicationAttachment,
    listApplicationCommands,
    createApplicationCommand,
    bulkSetApplicationCommands,
    getApplicationCommand,
    updateApplicationCommand,
    deleteApplicationCommand,
    listApplicationEmojis,
    createApplicationEmoji,
    getApplicationEmoji,
    updateApplicationEmoji,
    deleteApplicationEmoji,
    getEntitlements,
    createEntitlement,
    getEntitlement,
    deleteEntitlement,
    consumeEntitlement,
    listGuildApplicationCommands,
    createGuildApplicationCommand,
    bulkSetGuildApplicationCommands,
    listGuildApplicationCommandPermissions,
    getGuildApplicationCommand,
    updateGuildApplicationCommand,
    deleteGuildApplicationCommand,
    getGuildApplicationCommandPermissions,
    setGuildApplicationCommandPermissions,
    getApplicationRoleConnectionsMetadata,
    updateApplicationRoleConnectionsMetadata,
  ] ## All generated routes in this resource group.
