## Stable raw Discord HTTP routes in the `channels` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getChannel* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}",
    operationId: "get_channel",
    requestSchema: "",
    responseSchema: "GuildChannelResponse | PrivateChannelResponse | PrivateGroupChannelResponse | ThreadResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}` (`get_channel`).
  updateChannel* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/channels/{channel_id}",
    operationId: "update_channel",
    requestSchema: "UpdateDMRequestPartial | UpdateGroupDMRequestPartial | UpdateGuildChannelRequestPartial | UpdateThreadRequestPartial",
    responseSchema: "GuildChannelResponse | PrivateChannelResponse | PrivateGroupChannelResponse | ThreadResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /channels/{channel_id}` (`update_channel`).
  deleteChannel* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}",
    operationId: "delete_channel",
    requestSchema: "",
    responseSchema: "GuildChannelResponse | PrivateChannelResponse | PrivateGroupChannelResponse | ThreadResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}` (`delete_channel`).
  followChannel* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/followers",
    operationId: "follow_channel",
    requestSchema: "object",
    responseSchema: "ChannelFollowerResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/followers` (`follow_channel`).
  listChannelInvites* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/invites",
    operationId: "list_channel_invites",
    requestSchema: "",
    responseSchema: "seq[FriendInviteResponse | GroupDMInviteResponse | GuildInviteResponse | null] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/invites` (`list_channel_invites`).
  createChannelInvite* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/invites",
    operationId: "create_channel_invite",
    requestSchema: "CreateGroupDMInviteRequest | CreateGuildInviteRequest",
    responseSchema: "FriendInviteResponse | GroupDMInviteResponse | GuildInviteResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/invites` (`create_channel_invite`).
  listMessages* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/messages",
    operationId: "list_messages",
    requestSchema: "",
    responseSchema: "seq[MessageResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/messages` (`list_messages`).
  createMessage* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/messages",
    operationId: "create_message",
    requestSchema: "MessageCreateRequest",
    responseSchema: "MessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/messages` (`create_message`).
  bulkDeleteMessages* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/messages/bulk-delete",
    operationId: "bulk_delete_messages",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/messages/bulk-delete` (`bulk_delete_messages`).
  listPins* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/messages/pins",
    operationId: "list_pins",
    requestSchema: "",
    responseSchema: "PinnedMessagesResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/messages/pins` (`list_pins`).
  createPin* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/messages/pins/{message_id}",
    operationId: "create_pin",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/messages/pins/{message_id}` (`create_pin`).
  deletePin* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/pins/{message_id}",
    operationId: "delete_pin",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/pins/{message_id}` (`delete_pin`).
  getMessage* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}",
    operationId: "get_message",
    requestSchema: "",
    responseSchema: "MessageResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/messages/{message_id}` (`get_message`).
  updateMessage* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}",
    operationId: "update_message",
    requestSchema: "MessageEditRequestPartial",
    responseSchema: "MessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /channels/{channel_id}/messages/{message_id}` (`update_message`).
  deleteMessage* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}",
    operationId: "delete_message",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/{message_id}` (`delete_message`).
  crosspostMessage* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/crosspost",
    operationId: "crosspost_message",
    requestSchema: "",
    responseSchema: "MessageResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/messages/{message_id}/crosspost` (`crosspost_message`).
  deleteAllMessageReactions* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions",
    operationId: "delete_all_message_reactions",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/{message_id}/reactions` (`delete_all_message_reactions`).
  listMessageReactionsByEmoji* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}",
    operationId: "list_message_reactions_by_emoji",
    requestSchema: "",
    responseSchema: "seq[UserResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}` (`list_message_reactions_by_emoji`).
  deleteAllMessageReactionsByEmoji* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}",
    operationId: "delete_all_message_reactions_by_emoji",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}` (`delete_all_message_reactions_by_emoji`).
  addMyMessageReaction* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me",
    operationId: "add_my_message_reaction",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me` (`add_my_message_reaction`).
  deleteMyMessageReaction* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me",
    operationId: "delete_my_message_reaction",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me` (`delete_my_message_reaction`).
  deleteUserMessageReaction* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}",
    operationId: "delete_user_message_reaction",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}` (`delete_user_message_reaction`).
  createThreadFromMessage* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/messages/{message_id}/threads",
    operationId: "create_thread_from_message",
    requestSchema: "CreateTextThreadWithMessageRequest",
    responseSchema: "ThreadResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/messages/{message_id}/threads` (`create_thread_from_message`).
  setChannelPermissionOverwrite* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/permissions/{overwrite_id}",
    operationId: "set_channel_permission_overwrite",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/permissions/{overwrite_id}` (`set_channel_permission_overwrite`).
  deleteChannelPermissionOverwrite* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/permissions/{overwrite_id}",
    operationId: "delete_channel_permission_overwrite",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/permissions/{overwrite_id}` (`delete_channel_permission_overwrite`).
  deprecatedListPins* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/pins",
    operationId: "deprecated_list_pins",
    requestSchema: "",
    responseSchema: "seq[MessageResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/pins` (`deprecated_list_pins`).
  deprecatedCreatePin* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/pins/{message_id}",
    operationId: "deprecated_create_pin",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/pins/{message_id}` (`deprecated_create_pin`).
  deprecatedDeletePin* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/pins/{message_id}",
    operationId: "deprecated_delete_pin",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/pins/{message_id}` (`deprecated_delete_pin`).
  getAnswerVoters* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/polls/{message_id}/answers/{answer_id}",
    operationId: "get_answer_voters",
    requestSchema: "",
    responseSchema: "PollAnswerDetailsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/polls/{message_id}/answers/{answer_id}` (`get_answer_voters`).
  pollExpire* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/polls/{message_id}/expire",
    operationId: "poll_expire",
    requestSchema: "",
    responseSchema: "MessageResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/polls/{message_id}/expire` (`poll_expire`).
  addGroupDmUser* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/recipients/{user_id}",
    operationId: "add_group_dm_user",
    requestSchema: "object",
    responseSchema: "PrivateChannelResponse | PrivateGroupChannelResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/recipients/{user_id}` (`add_group_dm_user`).
  deleteGroupDmUser* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/recipients/{user_id}",
    operationId: "delete_group_dm_user",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/recipients/{user_id}` (`delete_group_dm_user`).
  sendSoundboardSound* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/send-soundboard-sound",
    operationId: "send_soundboard_sound",
    requestSchema: "SoundboardSoundSendRequest",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/send-soundboard-sound` (`send_soundboard_sound`).
  listThreadMembers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/thread-members",
    operationId: "list_thread_members",
    requestSchema: "",
    responseSchema: "seq[ThreadMemberResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/thread-members` (`list_thread_members`).
  joinThread* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/thread-members/@me",
    operationId: "join_thread",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/thread-members/@me` (`join_thread`).
  leaveThread* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/thread-members/@me",
    operationId: "leave_thread",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/thread-members/@me` (`leave_thread`).
  getThreadMember* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/thread-members/{user_id}",
    operationId: "get_thread_member",
    requestSchema: "",
    responseSchema: "ThreadMemberResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/thread-members/{user_id}` (`get_thread_member`).
  addThreadMember* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/thread-members/{user_id}",
    operationId: "add_thread_member",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/thread-members/{user_id}` (`add_thread_member`).
  deleteThreadMember* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/channels/{channel_id}/thread-members/{user_id}",
    operationId: "delete_thread_member",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /channels/{channel_id}/thread-members/{user_id}` (`delete_thread_member`).
  createThread* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/threads",
    operationId: "create_thread",
    requestSchema: "CreateForumThreadRequest | CreateTextThreadWithoutMessageRequest",
    responseSchema: "CreatedThreadResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/threads` (`create_thread`).
  listPrivateArchivedThreads* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/threads/archived/private",
    operationId: "list_private_archived_threads",
    requestSchema: "",
    responseSchema: "ThreadsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/threads/archived/private` (`list_private_archived_threads`).
  listPublicArchivedThreads* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/threads/archived/public",
    operationId: "list_public_archived_threads",
    requestSchema: "",
    responseSchema: "ThreadsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/threads/archived/public` (`list_public_archived_threads`).
  threadSearch* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/threads/search",
    operationId: "thread_search",
    requestSchema: "",
    responseSchema: "ThreadSearchResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/threads/search` (`thread_search`).
  triggerTypingIndicator* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/typing",
    operationId: "trigger_typing_indicator",
    requestSchema: "",
    responseSchema: "TypingIndicatorResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/typing` (`trigger_typing_indicator`).
  listMyPrivateArchivedThreads* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/users/@me/threads/archived/private",
    operationId: "list_my_private_archived_threads",
    requestSchema: "",
    responseSchema: "ThreadsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/users/@me/threads/archived/private` (`list_my_private_archived_threads`).
  updateVoiceChannelStatus* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/channels/{channel_id}/voice-status",
    operationId: "update_voice_channel_status",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /channels/{channel_id}/voice-status` (`update_voice_channel_status`).
  listChannelWebhooks* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/channels/{channel_id}/webhooks",
    operationId: "list_channel_webhooks",
    requestSchema: "",
    responseSchema: "seq[ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /channels/{channel_id}/webhooks` (`list_channel_webhooks`).
  createWebhook* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/channels/{channel_id}/webhooks",
    operationId: "create_webhook",
    requestSchema: "object",
    responseSchema: "GuildIncomingWebhookResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /channels/{channel_id}/webhooks` (`create_webhook`).
  channelsRoutes*: array[48, RawRoute] = [
    getChannel,
    updateChannel,
    deleteChannel,
    followChannel,
    listChannelInvites,
    createChannelInvite,
    listMessages,
    createMessage,
    bulkDeleteMessages,
    listPins,
    createPin,
    deletePin,
    getMessage,
    updateMessage,
    deleteMessage,
    crosspostMessage,
    deleteAllMessageReactions,
    listMessageReactionsByEmoji,
    deleteAllMessageReactionsByEmoji,
    addMyMessageReaction,
    deleteMyMessageReaction,
    deleteUserMessageReaction,
    createThreadFromMessage,
    setChannelPermissionOverwrite,
    deleteChannelPermissionOverwrite,
    deprecatedListPins,
    deprecatedCreatePin,
    deprecatedDeletePin,
    getAnswerVoters,
    pollExpire,
    addGroupDmUser,
    deleteGroupDmUser,
    sendSoundboardSound,
    listThreadMembers,
    joinThread,
    leaveThread,
    getThreadMember,
    addThreadMember,
    deleteThreadMember,
    createThread,
    listPrivateArchivedThreads,
    listPublicArchivedThreads,
    threadSearch,
    triggerTypingIndicator,
    listMyPrivateArchivedThreads,
    updateVoiceChannelStatus,
    listChannelWebhooks,
    createWebhook,
  ] ## All generated routes in this resource group.
