## Stable raw Discord HTTP routes in the `gateway` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getGateway* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/gateway",
    operationId: "get_gateway",
    requestSchema: "",
    responseSchema: "GatewayResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /gateway` (`get_gateway`).
  getBotGateway* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/gateway/bot",
    operationId: "get_bot_gateway",
    requestSchema: "",
    responseSchema: "GatewayBotResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /gateway/bot` (`get_bot_gateway`).
  gatewayRoutes*: array[2, RawRoute] = [
    getGateway,
    getBotGateway,
  ] ## All generated routes in this resource group.
