## Stable raw Discord HTTP routes in the `guilds` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getGuildTemplate* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/templates/{code}",
    operationId: "get_guild_template",
    requestSchema: "",
    responseSchema: "GuildTemplateResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/templates/{code}` (`get_guild_template`).
  getGuild* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}",
    operationId: "get_guild",
    requestSchema: "",
    responseSchema: "GuildWithCountsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}` (`get_guild`).
  updateGuild* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}",
    operationId: "update_guild",
    requestSchema: "GuildPatchRequestPartial",
    responseSchema: "GuildResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}` (`update_guild`).
  listGuildAuditLogEntries* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/audit-logs",
    operationId: "list_guild_audit_log_entries",
    requestSchema: "",
    responseSchema: "GuildAuditLogResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/audit-logs` (`list_guild_audit_log_entries`).
  listAutoModerationRules* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/auto-moderation/rules",
    operationId: "list_auto_moderation_rules",
    requestSchema: "",
    responseSchema: "seq[DefaultKeywordRuleResponse | KeywordRuleResponse | MLSpamRuleResponse | MentionSpamRuleResponse | UserProfileRuleResponse | null] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/auto-moderation/rules` (`list_auto_moderation_rules`).
  createAutoModerationRule* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/auto-moderation/rules",
    operationId: "create_auto_moderation_rule",
    requestSchema: "DefaultKeywordListUpsertRequest | KeywordUpsertRequest | MLSpamUpsertRequest | MentionSpamUpsertRequest | UserProfileUpsertRequest",
    responseSchema: "DefaultKeywordRuleResponse | KeywordRuleResponse | MLSpamRuleResponse | MentionSpamRuleResponse | UserProfileRuleResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/auto-moderation/rules` (`create_auto_moderation_rule`).
  getAutoModerationRule* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/auto-moderation/rules/{rule_id}",
    operationId: "get_auto_moderation_rule",
    requestSchema: "",
    responseSchema: "DefaultKeywordRuleResponse | KeywordRuleResponse | MLSpamRuleResponse | MentionSpamRuleResponse | UserProfileRuleResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/auto-moderation/rules/{rule_id}` (`get_auto_moderation_rule`).
  updateAutoModerationRule* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/auto-moderation/rules/{rule_id}",
    operationId: "update_auto_moderation_rule",
    requestSchema: "DefaultKeywordListUpsertRequestPartial | KeywordUpsertRequestPartial | MLSpamUpsertRequestPartial | MentionSpamUpsertRequestPartial | UserProfileUpsertRequestPartial",
    responseSchema: "DefaultKeywordRuleResponse | KeywordRuleResponse | MLSpamRuleResponse | MentionSpamRuleResponse | UserProfileRuleResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/auto-moderation/rules/{rule_id}` (`update_auto_moderation_rule`).
  deleteAutoModerationRule* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/auto-moderation/rules/{rule_id}",
    operationId: "delete_auto_moderation_rule",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/auto-moderation/rules/{rule_id}` (`delete_auto_moderation_rule`).
  listGuildBans* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/bans",
    operationId: "list_guild_bans",
    requestSchema: "",
    responseSchema: "seq[GuildBanResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/bans` (`list_guild_bans`).
  getGuildBan* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/bans/{user_id}",
    operationId: "get_guild_ban",
    requestSchema: "",
    responseSchema: "GuildBanResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/bans/{user_id}` (`get_guild_ban`).
  banUserFromGuild* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/bans/{user_id}",
    operationId: "ban_user_from_guild",
    requestSchema: "BanUserFromGuildRequest",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/bans/{user_id}` (`ban_user_from_guild`).
  unbanUserFromGuild* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/bans/{user_id}",
    operationId: "unban_user_from_guild",
    requestSchema: "UnbanUserFromGuildRequest",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/bans/{user_id}` (`unban_user_from_guild`).
  bulkBanUsersFromGuild* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/bulk-ban",
    operationId: "bulk_ban_users_from_guild",
    requestSchema: "BulkBanUsersRequest",
    responseSchema: "BulkBanUsersResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/bulk-ban` (`bulk_ban_users_from_guild`).
  listGuildChannels* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/channels",
    operationId: "list_guild_channels",
    requestSchema: "",
    responseSchema: "seq[GuildChannelResponse | PrivateChannelResponse | PrivateGroupChannelResponse | ThreadResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/channels` (`list_guild_channels`).
  createGuildChannel* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/channels",
    operationId: "create_guild_channel",
    requestSchema: "CreateGuildChannelRequest",
    responseSchema: "GuildChannelResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/channels` (`create_guild_channel`).
  bulkUpdateGuildChannels* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/channels",
    operationId: "bulk_update_guild_channels",
    requestSchema: "seq[object]",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/channels` (`bulk_update_guild_channels`).
  listGuildEmojis* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/emojis",
    operationId: "list_guild_emojis",
    requestSchema: "",
    responseSchema: "seq[EmojiResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/emojis` (`list_guild_emojis`).
  createGuildEmoji* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/emojis",
    operationId: "create_guild_emoji",
    requestSchema: "object",
    responseSchema: "EmojiResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/emojis` (`create_guild_emoji`).
  getGuildEmoji* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/emojis/{emoji_id}",
    operationId: "get_guild_emoji",
    requestSchema: "",
    responseSchema: "EmojiResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/emojis/{emoji_id}` (`get_guild_emoji`).
  updateGuildEmoji* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/emojis/{emoji_id}",
    operationId: "update_guild_emoji",
    requestSchema: "object",
    responseSchema: "EmojiResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/emojis/{emoji_id}` (`update_guild_emoji`).
  deleteGuildEmoji* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/emojis/{emoji_id}",
    operationId: "delete_guild_emoji",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/emojis/{emoji_id}` (`delete_guild_emoji`).
  updateGuildIncidentActions* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/incident-actions",
    operationId: "update_guild_incident_actions",
    requestSchema: "GuildIncidentActionsRequest",
    responseSchema: "GuildIncidentsDataResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/incident-actions` (`update_guild_incident_actions`).
  listGuildIntegrations* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/integrations",
    operationId: "list_guild_integrations",
    requestSchema: "",
    responseSchema: "seq[DiscordIntegrationResponse | ExternalConnectionIntegrationResponse | GuildSubscriptionIntegrationResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/integrations` (`list_guild_integrations`).
  deleteGuildIntegration* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/integrations/{integration_id}",
    operationId: "delete_guild_integration",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/integrations/{integration_id}` (`delete_guild_integration`).
  listGuildInvites* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/invites",
    operationId: "list_guild_invites",
    requestSchema: "",
    responseSchema: "seq[FriendInviteResponse | GroupDMInviteResponse | GuildInviteResponse | null] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/invites` (`list_guild_invites`).
  listGuildMembers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/members",
    operationId: "list_guild_members",
    requestSchema: "",
    responseSchema: "seq[GuildMemberResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/members` (`list_guild_members`).
  updateMyGuildMember* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/members/@me",
    operationId: "update_my_guild_member",
    requestSchema: "object",
    responseSchema: "PrivateGuildMemberResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/members/@me` (`update_my_guild_member`).
  searchGuildMembers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/members/search",
    operationId: "search_guild_members",
    requestSchema: "",
    responseSchema: "seq[GuildMemberResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/members/search` (`search_guild_members`).
  getGuildMember* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}",
    operationId: "get_guild_member",
    requestSchema: "",
    responseSchema: "GuildMemberResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/members/{user_id}` (`get_guild_member`).
  addGuildMember* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}",
    operationId: "add_guild_member",
    requestSchema: "BotAddGuildMemberRequest",
    responseSchema: "GuildMemberResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/members/{user_id}` (`add_guild_member`).
  updateGuildMember* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}",
    operationId: "update_guild_member",
    requestSchema: "object",
    responseSchema: "GuildMemberResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/members/{user_id}` (`update_guild_member`).
  deleteGuildMember* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}",
    operationId: "delete_guild_member",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/members/{user_id}` (`delete_guild_member`).
  addGuildMemberRole* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}/roles/{role_id}",
    operationId: "add_guild_member_role",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/members/{user_id}/roles/{role_id}` (`add_guild_member_role`).
  deleteGuildMemberRole* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/members/{user_id}/roles/{role_id}",
    operationId: "delete_guild_member_role",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/members/{user_id}/roles/{role_id}` (`delete_guild_member_role`).
  guildSearch* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/messages/search",
    operationId: "guild_search",
    requestSchema: "",
    responseSchema: "GuildSearchResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/messages/search` (`guild_search`).
  getGuildNewMemberWelcome* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/new-member-welcome",
    operationId: "get_guild_new_member_welcome",
    requestSchema: "",
    responseSchema: "GuildHomeSettingsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/new-member-welcome` (`get_guild_new_member_welcome`).
  getGuildsOnboarding* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/onboarding",
    operationId: "get_guilds_onboarding",
    requestSchema: "",
    responseSchema: "UserGuildOnboardingResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/onboarding` (`get_guilds_onboarding`).
  putGuildsOnboarding* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/onboarding",
    operationId: "put_guilds_onboarding",
    requestSchema: "UpdateGuildOnboardingRequest",
    responseSchema: "GuildOnboardingResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/onboarding` (`put_guilds_onboarding`).
  getGuildPreview* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/preview",
    operationId: "get_guild_preview",
    requestSchema: "",
    responseSchema: "GuildPreviewResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/preview` (`get_guild_preview`).
  previewPruneGuild* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/prune",
    operationId: "preview_prune_guild",
    requestSchema: "",
    responseSchema: "GuildPruneResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/prune` (`preview_prune_guild`).
  pruneGuild* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/prune",
    operationId: "prune_guild",
    requestSchema: "PruneGuildRequest",
    responseSchema: "GuildPruneResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/prune` (`prune_guild`).
  listGuildVoiceRegions* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/regions",
    operationId: "list_guild_voice_regions",
    requestSchema: "",
    responseSchema: "seq[VoiceRegionResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/regions` (`list_guild_voice_regions`).
  getGuildJoinRequests* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/requests",
    operationId: "get_guild_join_requests",
    requestSchema: "",
    responseSchema: "GuildJoinRequestsListResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/requests` (`get_guild_join_requests`).
  actionGuildJoinRequest* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/requests/{request_id}",
    operationId: "action_guild_join_request",
    requestSchema: "object",
    responseSchema: "GuildJoinRequestResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/requests/{request_id}` (`action_guild_join_request`).
  listGuildRoles* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/roles",
    operationId: "list_guild_roles",
    requestSchema: "",
    responseSchema: "seq[GuildRoleResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/roles` (`list_guild_roles`).
  createGuildRole* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/roles",
    operationId: "create_guild_role",
    requestSchema: "CreateRoleRequest",
    responseSchema: "GuildRoleResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/roles` (`create_guild_role`).
  bulkUpdateGuildRoles* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/roles",
    operationId: "bulk_update_guild_roles",
    requestSchema: "seq[UpdateRolePositionsRequest]",
    responseSchema: "seq[GuildRoleResponse]",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/roles` (`bulk_update_guild_roles`).
  guildRoleMemberCounts* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/roles/member-counts",
    operationId: "guild_role_member_counts",
    requestSchema: "",
    responseSchema: "object",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/roles/member-counts` (`guild_role_member_counts`).
  getGuildRole* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/roles/{role_id}",
    operationId: "get_guild_role",
    requestSchema: "",
    responseSchema: "GuildRoleResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/roles/{role_id}` (`get_guild_role`).
  updateGuildRole* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/roles/{role_id}",
    operationId: "update_guild_role",
    requestSchema: "UpdateRoleRequestPartial",
    responseSchema: "GuildRoleResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/roles/{role_id}` (`update_guild_role`).
  deleteGuildRole* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/roles/{role_id}",
    operationId: "delete_guild_role",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/roles/{role_id}` (`delete_guild_role`).
  listGuildScheduledEvents* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/scheduled-events",
    operationId: "list_guild_scheduled_events",
    requestSchema: "",
    responseSchema: "seq[ExternalScheduledEventResponse | StageScheduledEventResponse | VoiceScheduledEventResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/scheduled-events` (`list_guild_scheduled_events`).
  createGuildScheduledEvent* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/scheduled-events",
    operationId: "create_guild_scheduled_event",
    requestSchema: "ExternalScheduledEventCreateRequest | StageScheduledEventCreateRequest | VoiceScheduledEventCreateRequest",
    responseSchema: "ExternalScheduledEventResponse | StageScheduledEventResponse | VoiceScheduledEventResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/scheduled-events` (`create_guild_scheduled_event`).
  getGuildScheduledEvent* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
    operationId: "get_guild_scheduled_event",
    requestSchema: "",
    responseSchema: "ExternalScheduledEventResponse | StageScheduledEventResponse | VoiceScheduledEventResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}` (`get_guild_scheduled_event`).
  updateGuildScheduledEvent* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
    operationId: "update_guild_scheduled_event",
    requestSchema: "ExternalScheduledEventPatchRequestPartial | StageScheduledEventPatchRequestPartial | VoiceScheduledEventPatchRequestPartial",
    responseSchema: "ExternalScheduledEventResponse | StageScheduledEventResponse | VoiceScheduledEventResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}` (`update_guild_scheduled_event`).
  deleteGuildScheduledEvent* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
    operationId: "delete_guild_scheduled_event",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}` (`delete_guild_scheduled_event`).
  createGuildScheduledEventException* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions",
    operationId: "create_guild_scheduled_event_exception",
    requestSchema: "GuildScheduledEventExceptionCreateRequest",
    responseSchema: "GuildScheduledEventExceptionResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions` (`create_guild_scheduled_event_exception`).
  updateGuildScheduledEventException* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}",
    operationId: "update_guild_scheduled_event_exception",
    requestSchema: "GuildScheduledEventExceptionPatchRequestPartial",
    responseSchema: "GuildScheduledEventExceptionResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}` (`update_guild_scheduled_event_exception`).
  deleteGuildScheduledEventException* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}",
    operationId: "delete_guild_scheduled_event_exception",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}` (`delete_guild_scheduled_event_exception`).
  listGuildScheduledEventUsers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users",
    operationId: "list_guild_scheduled_event_users",
    requestSchema: "",
    responseSchema: "seq[ScheduledEventUserResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users` (`list_guild_scheduled_event_users`).
  countGuildScheduledEventUsers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts",
    operationId: "count_guild_scheduled_event_users",
    requestSchema: "",
    responseSchema: "ScheduledEventUserCountResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts` (`count_guild_scheduled_event_users`).
  listGuildScheduledEventExceptionUsers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users",
    operationId: "list_guild_scheduled_event_exception_users",
    requestSchema: "",
    responseSchema: "seq[ScheduledEventUserResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users` (`list_guild_scheduled_event_exception_users`).
  listGuildSoundboardSounds* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/soundboard-sounds",
    operationId: "list_guild_soundboard_sounds",
    requestSchema: "",
    responseSchema: "ListGuildSoundboardSoundsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/soundboard-sounds` (`list_guild_soundboard_sounds`).
  createGuildSoundboardSound* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/soundboard-sounds",
    operationId: "create_guild_soundboard_sound",
    requestSchema: "SoundboardCreateRequest",
    responseSchema: "SoundboardSoundResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/soundboard-sounds` (`create_guild_soundboard_sound`).
  getGuildSoundboardSound* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/soundboard-sounds/{sound_id}",
    operationId: "get_guild_soundboard_sound",
    requestSchema: "",
    responseSchema: "SoundboardSoundResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/soundboard-sounds/{sound_id}` (`get_guild_soundboard_sound`).
  updateGuildSoundboardSound* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/soundboard-sounds/{sound_id}",
    operationId: "update_guild_soundboard_sound",
    requestSchema: "SoundboardPatchRequestPartial",
    responseSchema: "SoundboardSoundResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/soundboard-sounds/{sound_id}` (`update_guild_soundboard_sound`).
  deleteGuildSoundboardSound* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/soundboard-sounds/{sound_id}",
    operationId: "delete_guild_soundboard_sound",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/soundboard-sounds/{sound_id}` (`delete_guild_soundboard_sound`).
  listGuildStickers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/stickers",
    operationId: "list_guild_stickers",
    requestSchema: "",
    responseSchema: "seq[GuildStickerResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/stickers` (`list_guild_stickers`).
  createGuildSticker* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/stickers",
    operationId: "create_guild_sticker",
    requestSchema: "object",
    responseSchema: "GuildStickerResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/stickers` (`create_guild_sticker`).
  getGuildSticker* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/stickers/{sticker_id}",
    operationId: "get_guild_sticker",
    requestSchema: "",
    responseSchema: "GuildStickerResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/stickers/{sticker_id}` (`get_guild_sticker`).
  updateGuildSticker* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/stickers/{sticker_id}",
    operationId: "update_guild_sticker",
    requestSchema: "object",
    responseSchema: "GuildStickerResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/stickers/{sticker_id}` (`update_guild_sticker`).
  deleteGuildSticker* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/stickers/{sticker_id}",
    operationId: "delete_guild_sticker",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/stickers/{sticker_id}` (`delete_guild_sticker`).
  listGuildTemplates* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/templates",
    operationId: "list_guild_templates",
    requestSchema: "",
    responseSchema: "seq[GuildTemplateResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/templates` (`list_guild_templates`).
  createGuildTemplate* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/guilds/{guild_id}/templates",
    operationId: "create_guild_template",
    requestSchema: "object",
    responseSchema: "GuildTemplateResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /guilds/{guild_id}/templates` (`create_guild_template`).
  syncGuildTemplate* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/guilds/{guild_id}/templates/{code}",
    operationId: "sync_guild_template",
    requestSchema: "",
    responseSchema: "GuildTemplateResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `PUT /guilds/{guild_id}/templates/{code}` (`sync_guild_template`).
  updateGuildTemplate* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/templates/{code}",
    operationId: "update_guild_template",
    requestSchema: "object",
    responseSchema: "GuildTemplateResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/templates/{code}` (`update_guild_template`).
  deleteGuildTemplate* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/guilds/{guild_id}/templates/{code}",
    operationId: "delete_guild_template",
    requestSchema: "",
    responseSchema: "GuildTemplateResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /guilds/{guild_id}/templates/{code}` (`delete_guild_template`).
  getActiveGuildThreads* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/threads/active",
    operationId: "get_active_guild_threads",
    requestSchema: "",
    responseSchema: "ThreadsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/threads/active` (`get_active_guild_threads`).
  getGuildVanityUrl* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/vanity-url",
    operationId: "get_guild_vanity_url",
    requestSchema: "",
    responseSchema: "VanityURLResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/vanity-url` (`get_guild_vanity_url`).
  getSelfVoiceState* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/voice-states/@me",
    operationId: "get_self_voice_state",
    requestSchema: "",
    responseSchema: "VoiceStateResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/voice-states/@me` (`get_self_voice_state`).
  updateSelfVoiceState* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/voice-states/@me",
    operationId: "update_self_voice_state",
    requestSchema: "UpdateSelfVoiceStateRequestPartial",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/voice-states/@me` (`update_self_voice_state`).
  getVoiceState* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/voice-states/{user_id}",
    operationId: "get_voice_state",
    requestSchema: "",
    responseSchema: "VoiceStateResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/voice-states/{user_id}` (`get_voice_state`).
  updateVoiceState* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/voice-states/{user_id}",
    operationId: "update_voice_state",
    requestSchema: "UpdateVoiceStateRequestPartial",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/voice-states/{user_id}` (`update_voice_state`).
  getGuildWebhooks* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/webhooks",
    operationId: "get_guild_webhooks",
    requestSchema: "",
    responseSchema: "seq[ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/webhooks` (`get_guild_webhooks`).
  getGuildWelcomeScreen* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/welcome-screen",
    operationId: "get_guild_welcome_screen",
    requestSchema: "",
    responseSchema: "GuildWelcomeScreenResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/welcome-screen` (`get_guild_welcome_screen`).
  updateGuildWelcomeScreen* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/welcome-screen",
    operationId: "update_guild_welcome_screen",
    requestSchema: "WelcomeScreenPatchRequestPartial",
    responseSchema: "GuildWelcomeScreenResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/welcome-screen` (`update_guild_welcome_screen`).
  getGuildWidgetSettings* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/widget",
    operationId: "get_guild_widget_settings",
    requestSchema: "",
    responseSchema: "WidgetSettingsResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/widget` (`get_guild_widget_settings`).
  updateGuildWidgetSettings* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/guilds/{guild_id}/widget",
    operationId: "update_guild_widget_settings",
    requestSchema: "object",
    responseSchema: "WidgetSettingsResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /guilds/{guild_id}/widget` (`update_guild_widget_settings`).
  getGuildWidget* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/widget.json",
    operationId: "get_guild_widget",
    requestSchema: "",
    responseSchema: "WidgetResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/widget.json` (`get_guild_widget`).
  getGuildWidgetPng* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/guilds/{guild_id}/widget.png",
    operationId: "get_guild_widget_png",
    requestSchema: "",
    responseSchema: "string",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /guilds/{guild_id}/widget.png` (`get_guild_widget_png`).
  guildsRoutes*: array[91, RawRoute] = [
    getGuildTemplate,
    getGuild,
    updateGuild,
    listGuildAuditLogEntries,
    listAutoModerationRules,
    createAutoModerationRule,
    getAutoModerationRule,
    updateAutoModerationRule,
    deleteAutoModerationRule,
    listGuildBans,
    getGuildBan,
    banUserFromGuild,
    unbanUserFromGuild,
    bulkBanUsersFromGuild,
    listGuildChannels,
    createGuildChannel,
    bulkUpdateGuildChannels,
    listGuildEmojis,
    createGuildEmoji,
    getGuildEmoji,
    updateGuildEmoji,
    deleteGuildEmoji,
    updateGuildIncidentActions,
    listGuildIntegrations,
    deleteGuildIntegration,
    listGuildInvites,
    listGuildMembers,
    updateMyGuildMember,
    searchGuildMembers,
    getGuildMember,
    addGuildMember,
    updateGuildMember,
    deleteGuildMember,
    addGuildMemberRole,
    deleteGuildMemberRole,
    guildSearch,
    getGuildNewMemberWelcome,
    getGuildsOnboarding,
    putGuildsOnboarding,
    getGuildPreview,
    previewPruneGuild,
    pruneGuild,
    listGuildVoiceRegions,
    getGuildJoinRequests,
    actionGuildJoinRequest,
    listGuildRoles,
    createGuildRole,
    bulkUpdateGuildRoles,
    guildRoleMemberCounts,
    getGuildRole,
    updateGuildRole,
    deleteGuildRole,
    listGuildScheduledEvents,
    createGuildScheduledEvent,
    getGuildScheduledEvent,
    updateGuildScheduledEvent,
    deleteGuildScheduledEvent,
    createGuildScheduledEventException,
    updateGuildScheduledEventException,
    deleteGuildScheduledEventException,
    listGuildScheduledEventUsers,
    countGuildScheduledEventUsers,
    listGuildScheduledEventExceptionUsers,
    listGuildSoundboardSounds,
    createGuildSoundboardSound,
    getGuildSoundboardSound,
    updateGuildSoundboardSound,
    deleteGuildSoundboardSound,
    listGuildStickers,
    createGuildSticker,
    getGuildSticker,
    updateGuildSticker,
    deleteGuildSticker,
    listGuildTemplates,
    createGuildTemplate,
    syncGuildTemplate,
    updateGuildTemplate,
    deleteGuildTemplate,
    getActiveGuildThreads,
    getGuildVanityUrl,
    getSelfVoiceState,
    updateSelfVoiceState,
    getVoiceState,
    updateVoiceState,
    getGuildWebhooks,
    getGuildWelcomeScreen,
    updateGuildWelcomeScreen,
    getGuildWidgetSettings,
    updateGuildWidgetSettings,
    getGuildWidget,
    getGuildWidgetPng,
  ] ## All generated routes in this resource group.
