## Stable raw Discord HTTP routes in the `interactions` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  createInteractionResponse* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/interactions/{interaction_id}/{interaction_token}/callback",
    operationId: "create_interaction_response",
    requestSchema: "ApplicationCommandAutocompleteCallbackRequest | CreateMessageInteractionCallbackRequest | LaunchActivityInteractionCallbackRequest | ModalInteractionCallbackRequest | PongInteractionCallbackRequest | SocialLayerSKUPurchaseEligibilityInteractionCallbackRequest | UpdateMessageInteractionCallbackRequest",
    responseSchema: "InteractionCallbackResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /interactions/{interaction_id}/{interaction_token}/callback` (`create_interaction_response`).
  interactionsRoutes*: array[1, RawRoute] = [
    createInteractionResponse,
  ] ## All generated routes in this resource group.
