## Stable raw Discord HTTP routes in the `invites` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  inviteResolve* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/invites/{code}",
    operationId: "invite_resolve",
    requestSchema: "",
    responseSchema: "FriendInviteResponse | GroupDMInviteResponse | GuildInviteResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /invites/{code}` (`invite_resolve`).
  inviteRevoke* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/invites/{code}",
    operationId: "invite_revoke",
    requestSchema: "",
    responseSchema: "FriendInviteResponse | GroupDMInviteResponse | GuildInviteResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /invites/{code}` (`invite_revoke`).
  getInviteTargetUsers* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/invites/{code}/target-users",
    operationId: "get_invite_target_users",
    requestSchema: "",
    responseSchema: "string",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /invites/{code}/target-users` (`get_invite_target_users`).
  updateInviteTargetUsers* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/invites/{code}/target-users",
    operationId: "update_invite_target_users",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /invites/{code}/target-users` (`update_invite_target_users`).
  getInviteTargetUsersJobStatus* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/invites/{code}/target-users/job-status",
    operationId: "get_invite_target_users_job_status",
    requestSchema: "",
    responseSchema: "TargetUsersJobStatusResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /invites/{code}/target-users/job-status` (`get_invite_target_users_job_status`).
  invitesRoutes*: array[5, RawRoute] = [
    inviteResolve,
    inviteRevoke,
    getInviteTargetUsers,
    updateInviteTargetUsers,
    getInviteTargetUsersJobStatus,
  ] ## All generated routes in this resource group.
