## Stable raw Discord HTTP routes in the `lobbies` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  createLobby* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/lobbies",
    operationId: "create_lobby",
    requestSchema: "object",
    responseSchema: "LobbyResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /lobbies` (`create_lobby`).
  createOrJoinLobby* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/lobbies",
    operationId: "create_or_join_lobby",
    requestSchema: "object",
    responseSchema: "LobbyResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /lobbies` (`create_or_join_lobby`).
  getLobby* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/lobbies/{lobby_id}",
    operationId: "get_lobby",
    requestSchema: "",
    responseSchema: "LobbyResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /lobbies/{lobby_id}` (`get_lobby`).
  editLobby* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/lobbies/{lobby_id}",
    operationId: "edit_lobby",
    requestSchema: "object",
    responseSchema: "LobbyResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /lobbies/{lobby_id}` (`edit_lobby`).
  deleteLobby* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/lobbies/{lobby_id}",
    operationId: "delete_lobby",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /lobbies/{lobby_id}` (`delete_lobby`).
  editLobbyChannelLink* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/lobbies/{lobby_id}/channel-linking",
    operationId: "edit_lobby_channel_link",
    requestSchema: "object",
    responseSchema: "LobbyResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /lobbies/{lobby_id}/channel-linking` (`edit_lobby_channel_link`).
  leaveLobby* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/lobbies/{lobby_id}/members/@me",
    operationId: "leave_lobby",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /lobbies/{lobby_id}/members/@me` (`leave_lobby`).
  createLinkedLobbyGuildInviteForSelf* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/lobbies/{lobby_id}/members/@me/invites",
    operationId: "create_linked_lobby_guild_invite_for_self",
    requestSchema: "",
    responseSchema: "LobbyGuildInviteResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /lobbies/{lobby_id}/members/@me/invites` (`create_linked_lobby_guild_invite_for_self`).
  bulkUpdateLobbyMembers* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/lobbies/{lobby_id}/members/bulk",
    operationId: "bulk_update_lobby_members",
    requestSchema: "seq[BulkLobbyMemberRequest] | null",
    responseSchema: "seq[LobbyMemberResponse] | null",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /lobbies/{lobby_id}/members/bulk` (`bulk_update_lobby_members`).
  addLobbyMember* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/lobbies/{lobby_id}/members/{user_id}",
    operationId: "add_lobby_member",
    requestSchema: "object",
    responseSchema: "LobbyMemberResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /lobbies/{lobby_id}/members/{user_id}` (`add_lobby_member`).
  deleteLobbyMember* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/lobbies/{lobby_id}/members/{user_id}",
    operationId: "delete_lobby_member",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /lobbies/{lobby_id}/members/{user_id}` (`delete_lobby_member`).
  createLinkedLobbyGuildInviteForUser* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/lobbies/{lobby_id}/members/{user_id}/invites",
    operationId: "create_linked_lobby_guild_invite_for_user",
    requestSchema: "",
    responseSchema: "LobbyGuildInviteResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `POST /lobbies/{lobby_id}/members/{user_id}/invites` (`create_linked_lobby_guild_invite_for_user`).
  getLobbyMessages* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/lobbies/{lobby_id}/messages",
    operationId: "get_lobby_messages",
    requestSchema: "",
    responseSchema: "seq[LobbyMessageResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /lobbies/{lobby_id}/messages` (`get_lobby_messages`).
  createLobbyMessage* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/lobbies/{lobby_id}/messages",
    operationId: "create_lobby_message",
    requestSchema: "SDKMessageRequest",
    responseSchema: "LobbyMessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /lobbies/{lobby_id}/messages` (`create_lobby_message`).
  updateLobbyMessageExternalModerationMetadata* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/lobbies/{lobby_id}/messages/{message_id}/moderation-metadata",
    operationId: "update_lobby_message_external_moderation_metadata",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /lobbies/{lobby_id}/messages/{message_id}/moderation-metadata` (`update_lobby_message_external_moderation_metadata`).
  lobbiesRoutes*: array[15, RawRoute] = [
    createLobby,
    createOrJoinLobby,
    getLobby,
    editLobby,
    deleteLobby,
    editLobbyChannelLink,
    leaveLobby,
    createLinkedLobbyGuildInviteForSelf,
    bulkUpdateLobbyMembers,
    addLobbyMember,
    deleteLobbyMember,
    createLinkedLobbyGuildInviteForUser,
    getLobbyMessages,
    createLobbyMessage,
    updateLobbyMessageExternalModerationMetadata,
  ] ## All generated routes in this resource group.
