## Stable raw Discord HTTP routes in the `oauth2` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getMyOauth2Authorization* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/oauth2/@me",
    operationId: "get_my_oauth2_authorization",
    requestSchema: "",
    responseSchema: "OAuth2GetAuthorizationResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /oauth2/@me` (`get_my_oauth2_authorization`).
  getMyOauth2Application* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/oauth2/applications/@me",
    operationId: "get_my_oauth2_application",
    requestSchema: "",
    responseSchema: "PrivateApplicationResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /oauth2/applications/@me` (`get_my_oauth2_application`).
  getPublicKeys* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/oauth2/keys",
    operationId: "get_public_keys",
    requestSchema: "",
    responseSchema: "OAuth2GetKeys",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /oauth2/keys` (`get_public_keys`).
  getOpenidConnectUserinfo* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/oauth2/userinfo",
    operationId: "get_openid_connect_userinfo",
    requestSchema: "",
    responseSchema: "OAuth2GetOpenIDConnectUserInfoResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /oauth2/userinfo` (`get_openid_connect_userinfo`).
  oauth2Routes*: array[4, RawRoute] = [
    getMyOauth2Authorization,
    getMyOauth2Application,
    getPublicKeys,
    getOpenidConnectUserinfo,
  ] ## All generated routes in this resource group.
