## Stable raw Discord HTTP routes in the `partner_sdk` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  updateUserMessageExternalModerationMetadata* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata",
    operationId: "update_user_message_external_moderation_metadata",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata` (`update_user_message_external_moderation_metadata`).
  partnerSdkUnmergeProvisionalAccount* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/partner-sdk/provisional-accounts/unmerge",
    operationId: "partner_sdk_unmerge_provisional_account",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /partner-sdk/provisional-accounts/unmerge` (`partner_sdk_unmerge_provisional_account`).
  botPartnerSdkUnmergeProvisionalAccount* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/partner-sdk/provisional-accounts/unmerge/bot",
    operationId: "bot_partner_sdk_unmerge_provisional_account",
    requestSchema: "object",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /partner-sdk/provisional-accounts/unmerge/bot` (`bot_partner_sdk_unmerge_provisional_account`).
  partnerSdkToken* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/partner-sdk/token",
    operationId: "partner_sdk_token",
    requestSchema: "object",
    responseSchema: "ProvisionalTokenResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /partner-sdk/token` (`partner_sdk_token`).
  botPartnerSdkToken* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/partner-sdk/token/bot",
    operationId: "bot_partner_sdk_token",
    requestSchema: "object",
    responseSchema: "ProvisionalTokenResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /partner-sdk/token/bot` (`bot_partner_sdk_token`).
  partnerSdkRoutes*: array[5, RawRoute] = [
    updateUserMessageExternalModerationMetadata,
    partnerSdkUnmergeProvisionalAccount,
    botPartnerSdkUnmergeProvisionalAccount,
    partnerSdkToken,
    botPartnerSdkToken,
  ] ## All generated routes in this resource group.
