## Stable raw Discord HTTP routes in the `skus` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getSkuSubscriptions* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/skus/{sku_id}/subscriptions",
    operationId: "get_sku_subscriptions",
    requestSchema: "",
    responseSchema: "seq[SubscriptionResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /skus/{sku_id}/subscriptions` (`get_sku_subscriptions`).
  getSkuSubscription* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/skus/{sku_id}/subscriptions/{subscription_id}",
    operationId: "get_sku_subscription",
    requestSchema: "",
    responseSchema: "SubscriptionResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /skus/{sku_id}/subscriptions/{subscription_id}` (`get_sku_subscription`).
  skusRoutes*: array[2, RawRoute] = [
    getSkuSubscriptions,
    getSkuSubscription,
  ] ## All generated routes in this resource group.
