## Stable raw Discord HTTP routes in the `stage_instances` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  createStageInstance* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/stage-instances",
    operationId: "create_stage_instance",
    requestSchema: "object",
    responseSchema: "StageInstanceResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /stage-instances` (`create_stage_instance`).
  getStageInstance* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/stage-instances/{channel_id}",
    operationId: "get_stage_instance",
    requestSchema: "",
    responseSchema: "StageInstanceResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /stage-instances/{channel_id}` (`get_stage_instance`).
  updateStageInstance* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/stage-instances/{channel_id}",
    operationId: "update_stage_instance",
    requestSchema: "object",
    responseSchema: "StageInstanceResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /stage-instances/{channel_id}` (`update_stage_instance`).
  deleteStageInstance* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/stage-instances/{channel_id}",
    operationId: "delete_stage_instance",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /stage-instances/{channel_id}` (`delete_stage_instance`).
  stageInstancesRoutes*: array[4, RawRoute] = [
    createStageInstance,
    getStageInstance,
    updateStageInstance,
    deleteStageInstance,
  ] ## All generated routes in this resource group.
