## Stable raw Discord HTTP routes in the `sticker_packs` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  listStickerPacks* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/sticker-packs",
    operationId: "list_sticker_packs",
    requestSchema: "",
    responseSchema: "StickerPackCollectionResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /sticker-packs` (`list_sticker_packs`).
  getStickerPack* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/sticker-packs/{pack_id}",
    operationId: "get_sticker_pack",
    requestSchema: "",
    responseSchema: "StickerPackResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /sticker-packs/{pack_id}` (`get_sticker_pack`).
  stickerPacksRoutes*: array[2, RawRoute] = [
    listStickerPacks,
    getStickerPack,
  ] ## All generated routes in this resource group.
