## Stable raw Discord HTTP routes in the `users` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getMyUser* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me",
    operationId: "get_my_user",
    requestSchema: "",
    responseSchema: "UserPIIResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me` (`get_my_user`).
  updateMyUser* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/users/@me",
    operationId: "update_my_user",
    requestSchema: "BotAccountPatchRequest",
    responseSchema: "UserPIIResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /users/@me` (`update_my_user`).
  getCurrentUserApplicationEntitlements* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me/applications/{application_id}/entitlements",
    operationId: "get_current_user_application_entitlements",
    requestSchema: "",
    responseSchema: "seq[EntitlementResponse]",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me/applications/{application_id}/entitlements` (`get_current_user_application_entitlements`).
  getApplicationUserRoleConnection* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me/applications/{application_id}/role-connection",
    operationId: "get_application_user_role_connection",
    requestSchema: "",
    responseSchema: "ApplicationUserRoleConnectionResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me/applications/{application_id}/role-connection` (`get_application_user_role_connection`).
  updateApplicationUserRoleConnection* = RawRoute(
    httpMethod: httpPut,
    pathTemplate: "/users/@me/applications/{application_id}/role-connection",
    operationId: "update_application_user_role_connection",
    requestSchema: "UpdateApplicationUserRoleConnectionRequest",
    responseSchema: "ApplicationUserRoleConnectionResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PUT /users/@me/applications/{application_id}/role-connection` (`update_application_user_role_connection`).
  deleteApplicationUserRoleConnection* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/users/@me/applications/{application_id}/role-connection",
    operationId: "delete_application_user_role_connection",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /users/@me/applications/{application_id}/role-connection` (`delete_application_user_role_connection`).
  createDm* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/users/@me/channels",
    operationId: "create_dm",
    requestSchema: "CreatePrivateChannelRequest",
    responseSchema: "PrivateChannelResponse | PrivateGroupChannelResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /users/@me/channels` (`create_dm`).
  listMyConnections* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me/connections",
    operationId: "list_my_connections",
    requestSchema: "",
    responseSchema: "seq[ConnectedAccountResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me/connections` (`list_my_connections`).
  listMyGuilds* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me/guilds",
    operationId: "list_my_guilds",
    requestSchema: "",
    responseSchema: "seq[MyGuildResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me/guilds` (`list_my_guilds`).
  leaveGuild* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/users/@me/guilds/{guild_id}",
    operationId: "leave_guild",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /users/@me/guilds/{guild_id}` (`leave_guild`).
  getMyGuildMember* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/@me/guilds/{guild_id}/member",
    operationId: "get_my_guild_member",
    requestSchema: "",
    responseSchema: "PrivateGuildMemberResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/@me/guilds/{guild_id}/member` (`get_my_guild_member`).
  getUser* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/users/{user_id}",
    operationId: "get_user",
    requestSchema: "",
    responseSchema: "UserResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /users/{user_id}` (`get_user`).
  usersRoutes*: array[12, RawRoute] = [
    getMyUser,
    updateMyUser,
    getCurrentUserApplicationEntitlements,
    getApplicationUserRoleConnection,
    updateApplicationUserRoleConnection,
    deleteApplicationUserRoleConnection,
    createDm,
    listMyConnections,
    listMyGuilds,
    leaveGuild,
    getMyGuildMember,
    getUser,
  ] ## All generated routes in this resource group.
