## Stable raw Discord HTTP routes in the `voice` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  listVoiceRegions* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/voice/regions",
    operationId: "list_voice_regions",
    requestSchema: "",
    responseSchema: "seq[VoiceRegionResponse] | null",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /voice/regions` (`list_voice_regions`).
  voiceRoutes*: array[1, RawRoute] = [
    listVoiceRegions,
  ] ## All generated routes in this resource group.
