## Stable raw Discord HTTP routes in the `webhooks` resource group.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

import ../route

const
  getWebhook* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/webhooks/{webhook_id}",
    operationId: "get_webhook",
    requestSchema: "",
    responseSchema: "ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /webhooks/{webhook_id}` (`get_webhook`).
  updateWebhook* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/webhooks/{webhook_id}",
    operationId: "update_webhook",
    requestSchema: "object",
    responseSchema: "ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /webhooks/{webhook_id}` (`update_webhook`).
  deleteWebhook* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/webhooks/{webhook_id}",
    operationId: "delete_webhook",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /webhooks/{webhook_id}` (`delete_webhook`).
  getWebhookByToken* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}",
    operationId: "get_webhook_by_token",
    requestSchema: "",
    responseSchema: "ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /webhooks/{webhook_id}/{webhook_token}` (`get_webhook_by_token`).
  executeWebhook* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}",
    operationId: "execute_webhook",
    requestSchema: "IncomingWebhookRequestPartial | IncomingWebhookUpdateRequestPartial",
    responseSchema: "MessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /webhooks/{webhook_id}/{webhook_token}` (`execute_webhook`).
  updateWebhookByToken* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}",
    operationId: "update_webhook_by_token",
    requestSchema: "object",
    responseSchema: "ApplicationIncomingWebhookResponse | ChannelFollowerWebhookResponse | GuildIncomingWebhookResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /webhooks/{webhook_id}/{webhook_token}` (`update_webhook_by_token`).
  deleteWebhookByToken* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}",
    operationId: "delete_webhook_by_token",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /webhooks/{webhook_id}/{webhook_token}` (`delete_webhook_by_token`).
  executeGithubCompatibleWebhook* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/github",
    operationId: "execute_github_compatible_webhook",
    requestSchema: "GithubWebhook",
    responseSchema: "",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /webhooks/{webhook_id}/{webhook_token}/github` (`execute_github_compatible_webhook`).
  getOriginalWebhookMessage* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/@original",
    operationId: "get_original_webhook_message",
    requestSchema: "",
    responseSchema: "MessageResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /webhooks/{webhook_id}/{webhook_token}/messages/@original` (`get_original_webhook_message`).
  updateOriginalWebhookMessage* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/@original",
    operationId: "update_original_webhook_message",
    requestSchema: "IncomingWebhookUpdateRequestPartial",
    responseSchema: "MessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /webhooks/{webhook_id}/{webhook_token}/messages/@original` (`update_original_webhook_message`).
  deleteOriginalWebhookMessage* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/@original",
    operationId: "delete_original_webhook_message",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /webhooks/{webhook_id}/{webhook_token}/messages/@original` (`delete_original_webhook_message`).
  getWebhookMessage* = RawRoute(
    httpMethod: httpGet,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
    operationId: "get_webhook_message",
    requestSchema: "",
    responseSchema: "MessageResponse",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `GET /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}` (`get_webhook_message`).
  updateWebhookMessage* = RawRoute(
    httpMethod: httpPatch,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
    operationId: "update_webhook_message",
    requestSchema: "IncomingWebhookUpdateRequestPartial",
    responseSchema: "MessageResponse",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `PATCH /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}` (`update_webhook_message`).
  deleteWebhookMessage* = RawRoute(
    httpMethod: httpDelete,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
    operationId: "delete_webhook_message",
    requestSchema: "",
    responseSchema: "",
    hasRequestBody: false,
    deprecated: false
  ) ## Route metadata for `DELETE /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}` (`delete_webhook_message`).
  executeSlackCompatibleWebhook* = RawRoute(
    httpMethod: httpPost,
    pathTemplate: "/webhooks/{webhook_id}/{webhook_token}/slack",
    operationId: "execute_slack_compatible_webhook",
    requestSchema: "SlackWebhook",
    responseSchema: "string | null",
    hasRequestBody: true,
    deprecated: false
  ) ## Route metadata for `POST /webhooks/{webhook_id}/{webhook_token}/slack` (`execute_slack_compatible_webhook`).
  webhooksRoutes*: array[15, RawRoute] = [
    getWebhook,
    updateWebhook,
    deleteWebhook,
    getWebhookByToken,
    executeWebhook,
    updateWebhookByToken,
    deleteWebhookByToken,
    executeGithubCompatibleWebhook,
    getOriginalWebhookMessage,
    updateOriginalWebhookMessage,
    deleteOriginalWebhookMessage,
    getWebhookMessage,
    updateWebhookMessage,
    deleteWebhookMessage,
    executeSlackCompatibleWebhook,
  ] ## All generated routes in this resource group.
