## Semantic model for the Discord message resource.

import std/[json, options]

import ./common
import ./user
import ./poll

export common
export user
export poll

type
  MessageType* = enum ## Discord message kinds; unknown values are preserved.
    mtDefault = 0 ## Standard user or bot message.
    mtRecipientAdd = 1 ## Recipient added to a group DM.
    mtRecipientRemove = 2 ## Recipient removed from a group DM.
    mtCall = 3 ## Call notification.
    mtChannelNameChange = 4 ## Group DM name changed.
    mtChannelIconChange = 5 ## Group DM icon changed.
    mtChannelPinnedMessage = 6 ## A message was pinned.
    mtUserJoin = 7 ## A member joined the guild.
    mtGuildBoost = 8 ## A member boosted the guild.
    mtReply = 19 ## Reply referencing another message.
    mtChatInputCommand = 20 ## Response to a slash command.
    mtThreadStarterMessage = 21 ## First message of a thread.
    mtContextMenuCommand = 23 ## Response to a context-menu command.

  Attachment* = object ## A file attached to a message.
    id*: AttachmentId ## Unique snowflake identity of the attachment.
    filename*: string ## Name of the attached file.
    description*: Option[string] ## Alt-text description, when set.
    contentType*: Option[string] ## Media type, when Discord reported it.
    size*: int64 ## File size in bytes.
    url*: string ## Source URL of the file.
    proxyUrl*: string ## Proxied URL of the file.
    height*: Option[int64] ## Image height, for images.
    width*: Option[int64] ## Image width, for images.
    ephemeral*: Option[bool] ## Whether the attachment is ephemeral.

  Reaction* = object ## A reaction tally on a message.
    count*: int64 ## Number of users who reacted with this emoji.
    me*: bool ## Whether the current user reacted with this emoji.
    emoji*: PartialEmoji ## Emoji the reaction uses.

  MessageEmbed* = object ## A rich embed attached to a message.
    kind*: string ## Embed type; required and non-null in a received message
                  ## (always `"rich"` for webhook embeds).
    title*: Option[string] ## Embed title, when present.
    description*: Option[string] ## Embed description, when present.
    url*: Option[string] ## Embed URL, when present.
    timestamp*: Option[Timestamp] ## Embed timestamp, when present.
    color*: Option[int64] ## Embed accent color, when present.

  MessageReferenceType* = enum ## Kind of a message reference.
    mrtDefault = 0 ## A reply or crosspost reference to another message.
    mrtForward = 1 ## A forwarded-message reference.

  MessageReference* = object ## A link from one received message to another.
    ##
    ## Models `MessageReferenceResponse`: on a received message `type` and
    ## `channel_id` are always present and non-null, unlike the outbound
    ## create-message request where both may be omitted. The response-specific
    ## shape is used here so a genuine reply or forward is never under-validated.
    kind*: OpenEnum[MessageReferenceType, int] ## Reference type wire value.
    channelId*: ChannelId ## Referenced channel; always present on a response.
    messageId*: Option[MessageId] ## Referenced message, when present.
    guildId*: Option[GuildId] ## Referenced guild, when present.

  MessageAuthorKind* = enum ## Which kind of author produced a message.
    makUser ## A real user or bot account authored the message.
    makWebhook ## A webhook generated the message.

  MessageAuthor* = object ## The author of a message.
    ##
    ## A message written by a user or bot carries a full, strictly-decoded
    ## `User`. A message generated by a webhook carries only the webhook's id,
    ## username, and avatar, which is not a valid full User. The two are modelled
    ## as distinct branches so callers pattern-match on `kind` rather than
    ## interpreting an `Option`, and the webhook branch keeps a `WebhookId`, not
    ## a `UserId`. The branch is chosen from the message's `webhook_id` before
    ## the author is decoded, so `decodeUser` is never weakened.
    case kind*: MessageAuthorKind
    of makUser:
      user*: User ## The full user or bot account behind the message.
    of makWebhook:
      webhookId*: WebhookId ## Webhook that generated the message.
      username*: string ## Webhook display name on this message.
      avatar*: Option[string] ## Webhook avatar hash, when set.

  BasicMessage* = object ## A decoded Discord message without nested tallies.
    ##
    ## Mirrors the pinned `BasicMessageResponse` boundary: it carries every
    ## field of a full message except `reactions` and `referenced_message`,
    ## which Discord never nests inside a referenced message. Using it for
    ## `Message.referencedMessage` keeps the type non-recursive.
    id*: MessageId ## Unique snowflake identity of the message.
    channelId*: ChannelId ## Channel the message was sent in.
    guildId*: Option[GuildId] ## Guild the message belongs to, when any.
    author*: MessageAuthor ## Account or webhook that sent the message.
    content*: string ## Message text, possibly empty.
    timestamp*: Timestamp ## When the message was sent.
    editedTimestamp*: Option[Timestamp] ## When last edited, else null.
    tts*: bool ## Whether the message was text-to-speech.
    mentionEveryone*: bool ## Whether the message mentioned everyone.
    mentions*: seq[User] ## Users directly mentioned.
    mentionRoles*: seq[RoleId] ## Roles directly mentioned.
    attachments*: seq[Attachment] ## Files attached to the message.
    embeds*: seq[MessageEmbed] ## Rich embeds on the message.
    pinned*: bool ## Whether the message is pinned.
    webhookId*: Option[WebhookId] ## Webhook that sent the message, when any.
    kind*: OpenEnum[MessageType, int] ## Message kind.
    flags*: int64 ## Message flag bits; always present, since MessageResponse
                  ## marks them required and non-null.
    messageReference*: Option[MessageReference] ## Reference metadata, when any.
    poll*: Option[Poll] ## Attached poll, when the message carries one.
    snapshot: DiscordSnapshot ## Retained decode evidence for the message.

  Message* = object ## A decoded Discord message.
    id*: MessageId ## Unique snowflake identity of the message.
    channelId*: ChannelId ## Channel the message was sent in.
    guildId*: Option[GuildId] ## Guild the message belongs to, when any.
    author*: MessageAuthor ## Account or webhook that sent the message.
    content*: string ## Message text, possibly empty.
    timestamp*: Timestamp ## When the message was sent.
    editedTimestamp*: Option[Timestamp] ## When last edited, else null.
    tts*: bool ## Whether the message was text-to-speech.
    mentionEveryone*: bool ## Whether the message mentioned everyone.
    mentions*: seq[User] ## Users directly mentioned.
    mentionRoles*: seq[RoleId] ## Roles directly mentioned.
    attachments*: seq[Attachment] ## Files attached to the message.
    embeds*: seq[MessageEmbed] ## Rich embeds on the message.
    pinned*: bool ## Whether the message is pinned.
    webhookId*: Option[WebhookId] ## Webhook that sent the message, when any.
    kind*: OpenEnum[MessageType, int] ## Message kind.
    flags*: int64 ## Message flag bits; always present, since MessageResponse
                  ## marks them required and non-null.
    messageReference*: Option[MessageReference] ## Reference metadata, when any.
    poll*: Option[Poll] ## Attached poll, when the message carries one.
    reactions*: seq[Reaction] ## Reaction tallies, when any exist.
    referencedMessage*: Option[BasicMessage] ## Inlined referenced message,
                                             ## when Discord resolved it.
    snapshot: DiscordSnapshot ## Retained decode evidence for the message.

proc decodeAttachment(node: JsonNode): Attachment =
  let obj = ensureObject(node, "message.attachment")
  result.id = decodeId(AttachmentId,
    requireField(obj, "id", "message.attachment"), "message.attachment.id")
  result.filename = asString(
    requireField(obj, "filename", "message.attachment"),
    "message.attachment.filename")
  result.description = optString(obj, "description", "message.attachment")
  result.contentType = optString(obj, "content_type", "message.attachment")
  result.size = asInt(
    requireField(obj, "size", "message.attachment"), "message.attachment.size")
  result.url = asString(
    requireField(obj, "url", "message.attachment"), "message.attachment.url")
  result.proxyUrl = asString(
    requireField(obj, "proxy_url", "message.attachment"),
    "message.attachment.proxy_url")
  result.height = optInt(obj, "height", "message.attachment")
  result.width = optInt(obj, "width", "message.attachment")
  result.ephemeral = optBool(obj, "ephemeral", "message.attachment")

proc decodeReactionEmoji(node: JsonNode): PartialEmoji =
  ## Decodes a `MessageReactionEmojiResponse`, where `id` and `name` are both
  ## required but nullable, so absence is rejected even though `null` is not.
  let obj = ensureObject(node, "message.reaction.emoji")
  result.id = reqNullableId(EmojiId, obj, "id", "message.reaction.emoji")
  result.name = reqNullableString(obj, "name", "message.reaction.emoji")
  result.animated = optBool(obj, "animated", "message.reaction.emoji")

proc decodeReaction(node: JsonNode): Reaction =
  let obj = ensureObject(node, "message.reaction")
  result.count = asInt(
    requireField(obj, "count", "message.reaction"), "message.reaction.count")
  result.me = asBool(
    requireField(obj, "me", "message.reaction"), "message.reaction.me")
  result.emoji = decodeReactionEmoji(
    requireField(obj, "emoji", "message.reaction"))
  # MessageReactionResponse also requires these, non-null and typed.
  requireNonNull(obj, "count_details", "message.reaction", {JObject})
  requireNonNull(obj, "burst_colors", "message.reaction", {JArray})
  requireNonNull(obj, "me_burst", "message.reaction", {JBool})

proc decodeEmbed(node: JsonNode): MessageEmbed =
  let obj = ensureObject(node, "message.embed")
  # `type` is required and non-null on a received embed. The official Message
  # Resource marks it optional in the general embed object, but for embeds
  # Discord actually returns it is always present (always "rich" for webhook
  # embeds); the pinned MessageEmbedResponse and this decoder require it.
  result.kind = asString(
    requireField(obj, "type", "message.embed"), "message.embed.type")
  result.title = optString(obj, "title", "message.embed")
  result.description = optString(obj, "description", "message.embed")
  result.url = optString(obj, "url", "message.embed")
  result.timestamp = optTimestamp(obj, "timestamp", "message.embed")
  result.color = optInt(obj, "color", "message.embed")

proc decodeMessageReference(node: JsonNode): MessageReference =
  let obj = ensureObject(node, "message.message_reference")
  result.kind = decodeIntEnum(MessageReferenceType,
    requireField(obj, "type", "message.message_reference"),
    "message.message_reference.type")
  result.channelId = decodeId(ChannelId,
    requireField(obj, "channel_id", "message.message_reference"),
    "message.message_reference.channel_id")
  result.messageId = optId(MessageId, obj, "message_id",
    "message.message_reference")
  result.guildId = optId(GuildId, obj, "guild_id",
    "message.message_reference")

proc decodeMessageAuthor*(node: JsonNode;
    webhookId: Option[WebhookId]): MessageAuthor =
  ## Decodes a message author into the branch selected by the message's
  ## `webhook_id`. A webhook-generated message carries only id, username, and
  ## avatar, which is not a valid full User, so it takes the webhook branch and
  ## keeps the `WebhookId`. Any other message is decoded strictly as a `User`.
  if webhookId.isSome:
    let obj = ensureObject(node, "message.author")
    let authorId = decodeId(WebhookId,
      requireField(obj, "id", "message.author"), "message.author.id")
    if authorId != webhookId.get:
      raiseDecode("message.author.id must match message.webhook_id")
    result = MessageAuthor(kind: makWebhook, webhookId: webhookId.get)
    result.username = asString(
      requireField(obj, "username", "message.author"),
      "message.author.username")
    result.avatar = reqNullableString(obj, "avatar", "message.author")
  else:
    result = MessageAuthor(kind: makUser, user: decodeUser(node))

template decodeMessageBody(target: untyped; obj: JsonNode) =
  ## Assigns the fields shared by `BasicMessage` and `Message`, enforcing the
  ## MessageResponse required-key list and nullability. `reactions`,
  ## `referenced_message`, and the retained snapshot are handled by each caller.
  target.id = decodeId(MessageId,
    requireField(obj, "id", "message"), "message.id")
  target.channelId = decodeId(ChannelId,
    requireField(obj, "channel_id", "message"), "message.channel_id")
  target.guildId = optId(GuildId, obj, "guild_id", "message")
  # Decode `webhook_id` before the author: a webhook-generated message carries a
  # partial author (id, username, avatar) that is not a valid full User, so the
  # author decode must know whether to apply the strict user contract.
  target.webhookId = optId(WebhookId, obj, "webhook_id", "message")
  target.author = decodeMessageAuthor(
    requireField(obj, "author", "message"), target.webhookId)
  target.content = asString(
    requireField(obj, "content", "message"), "message.content")
  target.timestamp = decodeTimestamp(
    requireField(obj, "timestamp", "message"), "message.timestamp")
  # `edited_timestamp` is required by MessageResponse but nullable.
  target.editedTimestamp = reqNullableTimestamp(
    obj, "edited_timestamp", "message")
  target.tts = asBool(requireField(obj, "tts", "message"), "message.tts")
  target.mentionEveryone = asBool(
    requireField(obj, "mention_everyone", "message"),
    "message.mention_everyone")
  for mentionNode in asArray(
      requireField(obj, "mentions", "message"), "message.mentions"):
    target.mentions.add(decodeUser(mentionNode))
  for index, roleNode in asArray(
      requireField(obj, "mention_roles", "message"), "message.mention_roles"):
    target.mentionRoles.add(decodeId(RoleId, roleNode,
      "message.mention_roles[" & $index & "]"))
  for attachmentNode in asArray(
      requireField(obj, "attachments", "message"), "message.attachments"):
    target.attachments.add(decodeAttachment(attachmentNode))
  for embedNode in asArray(
      requireField(obj, "embeds", "message"), "message.embeds"):
    target.embeds.add(decodeEmbed(embedNode))
  target.pinned = asBool(
    requireField(obj, "pinned", "message"), "message.pinned")
  target.kind = decodeIntEnum(MessageType,
    requireField(obj, "type", "message"), "message.type")
  # `flags` and `components` are required and non-null in MessageResponse.
  target.flags = asInt(requireField(obj, "flags", "message"), "message.flags")
  requireNonNull(obj, "components", "message", {JArray})
  let reference = optionalField(obj, "message_reference")
  if reference.isSome:
    target.messageReference = some(decodeMessageReference(reference.get))
  let poll = optionalField(obj, "poll")
  if poll.isSome:
    target.poll = some(decodePoll(poll.get))

const messageBodyConsumed = [
  "id", "channel_id", "guild_id", "author", "content", "timestamp",
  "edited_timestamp", "tts", "mention_everyone", "mentions", "mention_roles",
  "attachments", "embeds", "pinned", "webhook_id", "type", "flags",
  "components", "message_reference", "poll"]

proc decodeBasicMessage*(node: JsonNode): BasicMessage =
  ## Decodes a `BasicMessageResponse`, the referenced-message boundary.
  ##
  ## Rejects missing required fields but ignores any `reactions` or
  ## `referenced_message`, which Discord never nests here.
  let obj = ensureObject(node, "message")
  decodeMessageBody(result, obj)
  result.snapshot = initSnapshot(obj, messageBodyConsumed)

proc decodeMessage*(node: JsonNode): Message =
  ## Decodes a full Discord message object, rejecting missing required fields.
  let obj = ensureObject(node, "message")
  decodeMessageBody(result, obj)
  let reactions = optionalField(obj, "reactions")
  if reactions.isSome:
    for reactionNode in asArray(reactions.get, "message.reactions"):
      result.reactions.add(decodeReaction(reactionNode))
  # `referenced_message` is optional and nullable in MessageResponse.
  let referenced = optionalField(obj, "referenced_message")
  if referenced.isSome:
    result.referencedMessage = some(decodeBasicMessage(referenced.get))
  result.snapshot = initSnapshot(obj,
    @messageBodyConsumed & @["reactions", "referenced_message"])

proc parseMessage*(text: string): Message =
  ## Decodes a Discord message from a JSON document string.
  decodeMessage(parseJsonObject(text, "message"))

proc rawJson*(message: Message): JsonNode =
  ## Returns an independent deep copy of the message's original JSON.
  rawJson(message.snapshot)

proc unknownFields*(message: Message): seq[UnknownField] =
  ## Returns deep copies of message fields not consumed by the decoder.
  unknownFields(message.snapshot)

proc rawJson*(message: BasicMessage): JsonNode =
  ## Returns an independent deep copy of the basic message's original JSON.
  rawJson(message.snapshot)

proc unknownFields*(message: BasicMessage): seq[UnknownField] =
  ## Returns deep copies of basic-message fields not consumed by the decoder.
  ##
  ## Any `reactions` or `referenced_message` in the source appear here, since a
  ## `BasicMessage` does not model them.
  unknownFields(message.snapshot)
