## Deterministic generator for Cordnim's lossless raw Discord API surface.

import std/[algorithm, json, os, sets, strutils, tables]

type
  LockInfo = object
    apiVersion: int
    schemaRevision: string
    sourceRepository: string
    sourceCommit: string
    specRelativePath: string
    specSha256: string
    overlayRelativePath: string
    overlayRevision: int

  Operation = object
    resource: string
    path: string
    httpMethod: string
    operationId: string
    nimName: string
    requestSchema: string
    responseSchema: string
    hasRequestBody: bool
    deprecated: bool

  GeneratedFile = object
    relativePath: string
    content: string

  OverlayError* = object of ValueError ## Invalid semantic overlay input or a
    ## selector that cannot be applied.

  OverlaySemanticKind* {.pure.} = enum
    ## Semantic corrections understood by this generator.
    Snowflake
    ExtensibleBits
    PatchObject
    ExclusiveUnion
    OpenEnum
    IrreversibleComponentsV2Transition
    LegalComponentTree
    ModalLabelTree

  OverlayRepresentation* {.pure.} = enum
    ## Concrete representations supported for semantic corrections.
    DecimalStringAtJsonBoundary
    DecimalStringArbitraryWidth
    UnsetNullValue
    OneOf
    RawValuePlusKnownView
    SeparateLegacyAndV2Types
    ValidatedParentChildTreeMax40
    TypedFormSchemaAndDecoder

  OverlayRule* = object
    ## One validated overlay rule and the number of locations it matched.
    target*: string
    semantic*: OverlaySemanticKind
    representation*: OverlayRepresentation
    reason*: string
    matchCount*: int

  OverlayDescriptor* = object
    ## One concrete JSON Pointer produced by applying an overlay rule.
    jsonPointer*: string
    schemaName*: string
    propertyName*: string
    semantic*: OverlaySemanticKind
    representation*: OverlayRepresentation
    reason*: string
    ruleIndex*: int

  OverlayConstraints* = object
    ## Cross-cutting raw-layer constraints required by the overlay.
    preserveUnknownObjectFields*: bool
    preserveUnknownEnumValues*: bool
    preserveUnknownFlagBits*: bool
    treatOptionalAndNullableSeparately*: bool
    componentsV2Irreversible*: bool
    maximumMessageComponents*: int
    legacyAndV2MessageFieldsExclusive*: bool

  SemanticOverlayPlan* = object
    ## Fully validated and deterministically applied semantic overlay.
    revision*: int
    description*: string
    rules*: seq[OverlayRule]
    descriptors*: seq[OverlayDescriptor]
    constraints*: OverlayConstraints

  Selector = object
    source: string
    segments: seq[string]

  JsonLocation = object
    pointer: string
    segments: seq[string]
    node: JsonNode

const semanticExpectedShapes*: array[OverlaySemanticKind, string] = [
  "an OpenAPI scalar schema accepting string or integer snowflakes",
  "an OpenAPI scalar schema accepting string or integer bits, optionally null",
  "an OpenAPI object schema with a properties object",
  "the string value 'oneOf' used by x-discord-union",
  "a non-empty enum array containing one integer or string wire kind",
  "an object schema with components and flags properties",
  "an object component schema with a non-empty type enum",
  "an object modal-component schema with a non-empty type enum",
] ## Expected matched-node shape for every supported semantic kind.
  ##
  ## Shape validation is deliberately separate from selector matching. A
  ## broad selector that reaches an incompatible node is an overlay error; the
  ## generator never silently filters the bad match.

const generatedFileMarker* =
  "# Generated by tools/schema_codegen.nim; do not edit by hand."
  ## Marker used to distinguish generator-owned files from handwritten files.

const
  sha256RoundConstants: array[64, uint32] = [
    0x428a2f98'u32, 0x71374491'u32, 0xb5c0fbcf'u32, 0xe9b5dba5'u32,
    0x3956c25b'u32, 0x59f111f1'u32, 0x923f82a4'u32, 0xab1c5ed5'u32,
    0xd807aa98'u32, 0x12835b01'u32, 0x243185be'u32, 0x550c7dc3'u32,
    0x72be5d74'u32, 0x80deb1fe'u32, 0x9bdc06a7'u32, 0xc19bf174'u32,
    0xe49b69c1'u32, 0xefbe4786'u32, 0x0fc19dc6'u32, 0x240ca1cc'u32,
    0x2de92c6f'u32, 0x4a7484aa'u32, 0x5cb0a9dc'u32, 0x76f988da'u32,
    0x983e5152'u32, 0xa831c66d'u32, 0xb00327c8'u32, 0xbf597fc7'u32,
    0xc6e00bf3'u32, 0xd5a79147'u32, 0x06ca6351'u32, 0x14292967'u32,
    0x27b70a85'u32, 0x2e1b2138'u32, 0x4d2c6dfc'u32, 0x53380d13'u32,
    0x650a7354'u32, 0x766a0abb'u32, 0x81c2c92e'u32, 0x92722c85'u32,
    0xa2bfe8a1'u32, 0xa81a664b'u32, 0xc24b8b70'u32, 0xc76c51a3'u32,
    0xd192e819'u32, 0xd6990624'u32, 0xf40e3585'u32, 0x106aa070'u32,
    0x19a4c116'u32, 0x1e376c08'u32, 0x2748774c'u32, 0x34b0bcb5'u32,
    0x391c0cb3'u32, 0x4ed8aa4a'u32, 0x5b9cca4f'u32, 0x682e6ff3'u32,
    0x748f82ee'u32, 0x78a5636f'u32, 0x84c87814'u32, 0x8cc70208'u32,
    0x90befffa'u32, 0xa4506ceb'u32, 0xbef9a3f7'u32, 0xc67178f2'u32
  ]

func rotateRight(value: uint32, count: int): uint32 =
  (value shr count) or (value shl (32 - count))

func sha256Hex(input: string): string =
  # Keep schema verification self-contained so regeneration never depends on
  # the host's OpenSSL command or platform-specific crypto packages.
  var message = newSeqOfCap[byte](input.len + 72)
  for value in input:
    message.add byte(ord(value))
  message.add 0x80'u8
  while message.len mod 64 != 56:
    message.add 0'u8

  let bitLength = uint64(input.len) * 8'u64
  for shift in countdown(56, 0, 8):
    message.add byte((bitLength shr shift) and 0xff'u64)

  var hash = [
    0x6a09e667'u32, 0xbb67ae85'u32, 0x3c6ef372'u32, 0xa54ff53a'u32,
    0x510e527f'u32, 0x9b05688c'u32, 0x1f83d9ab'u32, 0x5be0cd19'u32
  ]

  var offset = 0
  while offset < message.len:
    var words: array[64, uint32]
    for index in 0..15:
      let start = offset + index * 4
      words[index] =
        (uint32(message[start]) shl 24) or
        (uint32(message[start + 1]) shl 16) or
        (uint32(message[start + 2]) shl 8) or
        uint32(message[start + 3])
    for index in 16..63:
      let sigma0 = rotateRight(words[index - 15], 7) xor
        rotateRight(words[index - 15], 18) xor
        (words[index - 15] shr 3)
      let sigma1 = rotateRight(words[index - 2], 17) xor
        rotateRight(words[index - 2], 19) xor
        (words[index - 2] shr 10)
      words[index] = words[index - 16] + sigma0 +
        words[index - 7] + sigma1

    var a = hash[0]
    var b = hash[1]
    var c = hash[2]
    var d = hash[3]
    var e = hash[4]
    var f = hash[5]
    var g = hash[6]
    var h = hash[7]

    for index in 0..63:
      let choice = (e and f) xor ((not e) and g)
      let majority = (a and b) xor (a and c) xor (b and c)
      let bigSigma0 = rotateRight(a, 2) xor rotateRight(a, 13) xor
        rotateRight(a, 22)
      let bigSigma1 = rotateRight(e, 6) xor rotateRight(e, 11) xor
        rotateRight(e, 25)
      let temporary1 = h + bigSigma1 + choice +
        sha256RoundConstants[index] + words[index]
      let temporary2 = bigSigma0 + majority

      h = g
      g = f
      f = e
      e = d + temporary1
      d = c
      c = b
      b = a
      a = temporary1 + temporary2

    hash[0] = hash[0] + a
    hash[1] = hash[1] + b
    hash[2] = hash[2] + c
    hash[3] = hash[3] + d
    hash[4] = hash[4] + e
    hash[5] = hash[5] + f
    hash[6] = hash[6] + g
    hash[7] = hash[7] + h
    offset += 64

  for value in hash:
    result.add toHex(value, 8).toLowerAscii

proc fail(message: string) {.noreturn.} =
  quit "schema_codegen: " & message

proc requireObject(node: JsonNode, description: string) =
  if node.isNil or node.kind != JObject:
    fail description & " must be a JSON object"

proc requiredString(node: JsonNode, key: string): string =
  node.requireObject("document")
  if not node.hasKey(key) or node[key].kind != JString:
    fail "missing string field: " & key
  node[key].getStr

proc requiredInt(node: JsonNode, key: string): int =
  node.requireObject("document")
  if not node.hasKey(key) or node[key].kind != JInt:
    fail "missing integer field: " & key
  node[key].getInt

proc sortedKeys(node: JsonNode): seq[string] =
  node.requireObject("value")
  for key, _ in node.fields:
    result.add key
  result.sort

proc overlayFailure(message: string) {.noreturn.} =
  raise newException(OverlayError, message)

proc requireOverlayObject(node: JsonNode; description: string) =
  if node.isNil or node.kind != JObject:
    overlayFailure(description & " must be a JSON object")

proc validateOverlayKeys(
    node: JsonNode; allowed: openArray[string]; description: string
) =
  node.requireOverlayObject(description)
  for key, _ in node.fields:
    if key notin allowed:
      overlayFailure(description & " has unknown field: " & key)

proc overlayString(
    node: JsonNode; key, description: string
): string =
  node.requireOverlayObject(description)
  if not node.hasKey(key) or node[key].kind != JString:
    overlayFailure(description & " requires string field: " & key)
  result = node[key].getStr
  if result.len == 0:
    overlayFailure(description & " field must not be empty: " & key)

proc overlayTargets(node: JsonNode; description: string): seq[string] =
  node.requireOverlayObject(description)
  if not node.hasKey("target"):
    overlayFailure(description & " requires field: target")
  let target = node["target"]
  case target.kind
  of JString:
    if target.getStr.len == 0:
      overlayFailure(description & " target must not be empty")
    result.add target.getStr
  of JArray:
    if target.len == 0:
      overlayFailure(description & " target array must not be empty")
    for index in 0..<target.len:
      if target[index].kind != JString or target[index].getStr.len == 0:
        overlayFailure(
          description & " target array requires non-empty strings at index " &
            $index
        )
      result.add target[index].getStr
  else:
    overlayFailure(description & " target must be a string or string array")

proc overlayInt(node: JsonNode; key, description: string): int =
  node.requireOverlayObject(description)
  if not node.hasKey(key) or node[key].kind != JInt:
    overlayFailure(description & " requires integer field: " & key)
  node[key].getInt

proc overlayBool(node: JsonNode; key, description: string): bool =
  node.requireOverlayObject(description)
  if not node.hasKey(key) or node[key].kind != JBool:
    overlayFailure(description & " requires boolean field: " & key)
  node[key].getBool

proc parseSemantic(value: string): OverlaySemanticKind =
  case value
  of "snowflake": OverlaySemanticKind.Snowflake
  of "extensible-bits": OverlaySemanticKind.ExtensibleBits
  of "patch-object": OverlaySemanticKind.PatchObject
  of "exclusive-union": OverlaySemanticKind.ExclusiveUnion
  of "open-enum": OverlaySemanticKind.OpenEnum
  of "irreversible-components-v2-transition":
    OverlaySemanticKind.IrreversibleComponentsV2Transition
  of "legal-component-tree": OverlaySemanticKind.LegalComponentTree
  of "modal-label-tree": OverlaySemanticKind.ModalLabelTree
  else:
    overlayFailure("unknown overlay semantic: " & value)

proc parseRepresentation(value: string): OverlayRepresentation =
  case value
  of "decimal-string-at-json-boundary":
    OverlayRepresentation.DecimalStringAtJsonBoundary
  of "decimal-string-arbitrary-width":
    OverlayRepresentation.DecimalStringArbitraryWidth
  of "unset-null-value": OverlayRepresentation.UnsetNullValue
  of "one-of": OverlayRepresentation.OneOf
  of "raw-value-plus-known-view":
    OverlayRepresentation.RawValuePlusKnownView
  of "separate-legacy-and-v2-types":
    OverlayRepresentation.SeparateLegacyAndV2Types
  of "validated-parent-child-tree-max-40":
    OverlayRepresentation.ValidatedParentChildTreeMax40
  of "typed-form-schema-and-decoder":
    OverlayRepresentation.TypedFormSchemaAndDecoder
  else:
    overlayFailure("unknown overlay representation: " & value)

func semanticWire(value: OverlaySemanticKind): string =
  case value
  of OverlaySemanticKind.Snowflake: "snowflake"
  of OverlaySemanticKind.ExtensibleBits: "extensible-bits"
  of OverlaySemanticKind.PatchObject: "patch-object"
  of OverlaySemanticKind.ExclusiveUnion: "exclusive-union"
  of OverlaySemanticKind.OpenEnum: "open-enum"
  of OverlaySemanticKind.IrreversibleComponentsV2Transition:
    "irreversible-components-v2-transition"
  of OverlaySemanticKind.LegalComponentTree: "legal-component-tree"
  of OverlaySemanticKind.ModalLabelTree: "modal-label-tree"

func representationWire(value: OverlayRepresentation): string =
  case value
  of OverlayRepresentation.DecimalStringAtJsonBoundary:
    "decimal-string-at-json-boundary"
  of OverlayRepresentation.DecimalStringArbitraryWidth:
    "decimal-string-arbitrary-width"
  of OverlayRepresentation.UnsetNullValue: "unset-null-value"
  of OverlayRepresentation.OneOf: "one-of"
  of OverlayRepresentation.RawValuePlusKnownView:
    "raw-value-plus-known-view"
  of OverlayRepresentation.SeparateLegacyAndV2Types:
    "separate-legacy-and-v2-types"
  of OverlayRepresentation.ValidatedParentChildTreeMax40:
    "validated-parent-child-tree-max-40"
  of OverlayRepresentation.TypedFormSchemaAndDecoder:
    "typed-form-schema-and-decoder"

proc validateSemanticPair(
    semantic: OverlaySemanticKind; representation: OverlayRepresentation
) =
  let valid = case semantic
    of OverlaySemanticKind.Snowflake:
      representation == OverlayRepresentation.DecimalStringAtJsonBoundary
    of OverlaySemanticKind.ExtensibleBits:
      representation == OverlayRepresentation.DecimalStringArbitraryWidth
    of OverlaySemanticKind.PatchObject:
      representation == OverlayRepresentation.UnsetNullValue
    of OverlaySemanticKind.ExclusiveUnion:
      representation == OverlayRepresentation.OneOf
    of OverlaySemanticKind.OpenEnum:
      representation == OverlayRepresentation.RawValuePlusKnownView
    of OverlaySemanticKind.IrreversibleComponentsV2Transition:
      representation == OverlayRepresentation.SeparateLegacyAndV2Types
    of OverlaySemanticKind.LegalComponentTree:
      representation ==
        OverlayRepresentation.ValidatedParentChildTreeMax40
    of OverlaySemanticKind.ModalLabelTree:
      representation == OverlayRepresentation.TypedFormSchemaAndDecoder
  if not valid:
    overlayFailure(
      "representation " & representation.representationWire &
        " is not valid for semantic " & semantic.semanticWire
    )

proc decodePointerSegment(value: string): string =
  var index = 0
  while index < value.len:
    if value[index] == '~':
      if index + 1 >= value.len or value[index + 1] notin {'0', '1'}:
        overlayFailure("malformed JSON Pointer escape in selector segment")
      if value[index + 1] == '0':
        result.add '~'
      else:
        result.add '/'
      index += 2
    else:
      result.add value[index]
      inc index

proc parseSelectorAlternative(value: string): Selector =
  if value.len == 0 or value.strip != value:
    overlayFailure("overlay selector alternatives must not be empty or padded")

  let rawSegments = if value.startsWith("#/"):
    value[2..^1].split('/')
  elif value.startsWith("**/"):
    value.split('/')
  else:
    overlayFailure(
      "selector must start with '#/' or '**/': " & value
    )

  result.source = value
  for rawSegment in rawSegments:
    if rawSegment.len == 0:
      overlayFailure("selector contains an empty segment: " & value)
    if rawSegment == "**":
      result.segments.add rawSegment
    else:
      if rawSegment.contains("**") or rawSegment.count('*') > 1:
        overlayFailure("malformed wildcard segment in selector: " & value)
      result.segments.add rawSegment.decodePointerSegment

proc parseSelector(value: string): seq[Selector] =
  for alternative in value.split('|'):
    result.add alternative.parseSelectorAlternative
  if result.len == 0:
    overlayFailure("overlay selector must contain an alternative")

func segmentMatches(pattern, value: string): bool =
  let wildcard = pattern.find('*')
  if wildcard < 0:
    return pattern == value
  let prefix = pattern[0..<wildcard]
  let suffix = if wildcard + 1 < pattern.len:
    pattern[wildcard + 1..^1]
  else:
    ""
  value.len >= prefix.len + suffix.len and value.startsWith(prefix) and
    value.endsWith(suffix)

func selectorMatchesAt(
    pattern, value: openArray[string]; patternIndex, valueIndex: int
): bool =
  if patternIndex == pattern.len:
    return valueIndex == value.len
  if pattern[patternIndex] == "**":
    for nextIndex in valueIndex..value.len:
      if selectorMatchesAt(
          pattern, value, patternIndex + 1, nextIndex
      ):
        return true
    return false
  valueIndex < value.len and
    segmentMatches(pattern[patternIndex], value[valueIndex]) and
    selectorMatchesAt(pattern, value, patternIndex + 1, valueIndex + 1)

func matches(selector: Selector; location: JsonLocation): bool =
  selectorMatchesAt(selector.segments, location.segments, 0, 0)

func scalarWireSchemaMatches(node: JsonNode; allowNull: bool): bool =
  if node.isNil or node.kind != JObject or not node.hasKey("type"):
    return false

  var hasWireType = false
  proc validType(value: JsonNode): bool =
    if value.kind != JString:
      return false
    case value.getStr
    of "string", "integer":
      hasWireType = true
      true
    of "null":
      allowNull
    else:
      false

  let schemaType = node["type"]
  case schemaType.kind
  of JString:
    result = validType(schemaType) and hasWireType
  of JArray:
    if schemaType.len == 0:
      return false
    result = true
    for value in schemaType.items:
      if not validType(value):
        result = false
    result = result and hasWireType
  else:
    result = false

func objectSchemaMatches(node: JsonNode): bool =
  node != nil and node.kind == JObject and node.hasKey("type") and
    node["type"].kind == JString and node["type"].getStr == "object" and
    node.hasKey("properties") and node["properties"].kind == JObject

func objectSchemaHasProperties(
    node: JsonNode; propertyNames: openArray[string]
): bool =
  if not objectSchemaMatches(node):
    return false
  for propertyName in propertyNames:
    if not node["properties"].hasKey(propertyName):
      return false
  true

func openEnumMatches(node: JsonNode): bool =
  if node.isNil or node.kind != JArray or node.len == 0:
    return false
  var wireKind = JNull
  for value in node.items:
    if value.kind notin {JInt, JString}:
      return false
    if wireKind == JNull:
      wireKind = value.kind
    elif value.kind != wireKind:
      return false
  true

func componentSchemaMatches(node: JsonNode): bool =
  objectSchemaHasProperties(node, ["type"]) and
    node["properties"]["type"].kind == JObject and
    node["properties"]["type"].hasKey("enum") and
    openEnumMatches(node["properties"]["type"]["enum"])

func observedShape(node: JsonNode): string =
  if node.isNil:
    return "nil"
  case node.kind
  of JObject:
    if node.hasKey("type"):
      "OpenAPI schema with type " & $node["type"]
    else:
      "OpenAPI object without a type"
  of JArray:
    "JSON array with " & $node.len & " item(s)"
  of JString:
    "JSON string '" & node.getStr & "'"
  else:
    "JSON " & $node.kind

proc validateSemanticNode(
    rule: OverlayRule; selector: string; location: JsonLocation
) =
  let valid = case rule.semantic
    of OverlaySemanticKind.Snowflake:
      scalarWireSchemaMatches(location.node, allowNull = false)
    of OverlaySemanticKind.ExtensibleBits:
      scalarWireSchemaMatches(location.node, allowNull = true)
    of OverlaySemanticKind.PatchObject:
      objectSchemaMatches(location.node)
    of OverlaySemanticKind.IrreversibleComponentsV2Transition:
      objectSchemaHasProperties(location.node, ["components", "flags"])
    of OverlaySemanticKind.LegalComponentTree,
        OverlaySemanticKind.ModalLabelTree:
      componentSchemaMatches(location.node)
    of OverlaySemanticKind.ExclusiveUnion:
      location.node != nil and location.node.kind == JString and
        location.node.getStr == "oneOf"
    of OverlaySemanticKind.OpenEnum:
      openEnumMatches(location.node)

  if not valid:
    overlayFailure(
      "semantic '" & rule.semantic.semanticWire & "' selector '" &
        selector & "' matched incompatible node " & location.pointer &
        "; expected " & semanticExpectedShapes[rule.semantic] &
        "; observed " & location.node.observedShape
    )

func encodePointerSegment(value: string): string =
  value.replace("~", "~0").replace("/", "~1")

func toJsonPointer(segments: openArray[string]): string =
  result = "#"
  for segment in segments:
    result.add '/'
    result.add segment.encodePointerSegment

proc collectJsonLocations(
    node: JsonNode; segments: var seq[string]; locations: var seq[JsonLocation]
) =
  var copiedSegments: seq[string]
  for segment in segments:
    copiedSegments.add segment
  locations.add JsonLocation(
    pointer: copiedSegments.toJsonPointer,
    segments: copiedSegments,
    node: node,
  )

  case node.kind
  of JObject:
    var keys: seq[string]
    for key, _ in node.fields:
      keys.add key
    keys.sort
    for key in keys:
      segments.add key
      collectJsonLocations(node[key], segments, locations)
      segments.setLen(segments.len - 1)
  of JArray:
    for index in 0..<node.len:
      segments.add $index
      collectJsonLocations(node[index], segments, locations)
      segments.setLen(segments.len - 1)
  else:
    discard

func descriptorSchemaName(segments: openArray[string]): string =
  if segments.len >= 3 and segments[0] == "components" and
      segments[1] == "schemas":
    segments[2]
  else:
    ""

func descriptorPropertyName(segments: openArray[string]): string =
  if segments.len >= 2:
    for index in 0..<(segments.len - 1):
      if segments[index] == "properties":
        result = segments[index + 1]

proc parseOverlayConstraints(node: JsonNode): OverlayConstraints =
  const allowed = [
    "preserveUnknownObjectFields",
    "preserveUnknownEnumValues",
    "preserveUnknownFlagBits",
    "treatOptionalAndNullableSeparately",
    "componentsV2Irreversible",
    "maximumMessageComponents",
    "legacyAndV2MessageFieldsExclusive",
  ]
  node.validateOverlayKeys(allowed, "overlay constraints")
  result.preserveUnknownObjectFields = node.overlayBool(
    "preserveUnknownObjectFields", "overlay constraints"
  )
  result.preserveUnknownEnumValues = node.overlayBool(
    "preserveUnknownEnumValues", "overlay constraints"
  )
  result.preserveUnknownFlagBits = node.overlayBool(
    "preserveUnknownFlagBits", "overlay constraints"
  )
  result.treatOptionalAndNullableSeparately = node.overlayBool(
    "treatOptionalAndNullableSeparately", "overlay constraints"
  )
  result.componentsV2Irreversible = node.overlayBool(
    "componentsV2Irreversible", "overlay constraints"
  )
  result.maximumMessageComponents = node.overlayInt(
    "maximumMessageComponents", "overlay constraints"
  )
  result.legacyAndV2MessageFieldsExclusive = node.overlayBool(
    "legacyAndV2MessageFieldsExclusive", "overlay constraints"
  )
  if result.maximumMessageComponents <= 0:
    overlayFailure("maximumMessageComponents must be positive")
  for invariant in [
    ("preserveUnknownObjectFields",
      result.preserveUnknownObjectFields),
    ("preserveUnknownEnumValues", result.preserveUnknownEnumValues),
    ("preserveUnknownFlagBits", result.preserveUnknownFlagBits),
    ("treatOptionalAndNullableSeparately",
      result.treatOptionalAndNullableSeparately),
    ("componentsV2Irreversible", result.componentsV2Irreversible),
    ("legacyAndV2MessageFieldsExclusive",
      result.legacyAndV2MessageFieldsExclusive),
  ]:
    if not invariant[1]:
      overlayFailure(
        "overlay constraint " & invariant[0] &
          " must be true for the current implementation"
      )
  if result.maximumMessageComponents != 40:
    overlayFailure(
      "overlay constraint maximumMessageComponents must be 40 for the " &
        "current implementation"
    )

proc applySemanticOverlay*(
    spec, overlay: JsonNode
): SemanticOverlayPlan =
  ## Validates and applies every semantic rule to concrete OpenAPI locations.
  ##
  ## Every selector alternative must match. Multiple rules may not own the
  ## same location, even if their semantic declarations are identical.
  const topLevelKeys = ["revision", "description", "rules", "constraints"]
  const ruleKeys = ["target", "semantic", "representation", "reason"]

  spec.requireOverlayObject("OpenAPI document")
  overlay.validateOverlayKeys(topLevelKeys, "semantic overlay")
  result.revision = overlay.overlayInt("revision", "semantic overlay")
  if result.revision <= 0:
    overlayFailure("semantic overlay revision must be positive")
  result.description = overlay.overlayString(
    "description", "semantic overlay"
  )
  if not overlay.hasKey("rules") or overlay["rules"].kind != JArray:
    overlayFailure("semantic overlay requires array field: rules")
  if overlay["rules"].len == 0:
    overlayFailure("semantic overlay must contain at least one rule")
  if not overlay.hasKey("constraints"):
    overlayFailure("semantic overlay requires object field: constraints")
  result.constraints = parseOverlayConstraints(overlay["constraints"])

  var selectors: seq[seq[Selector]]
  var targets = initHashSet[string]()
  for index in 0..<overlay["rules"].len:
    let node = overlay["rules"][index]
    let description = "semantic overlay rule " & $index
    node.validateOverlayKeys(ruleKeys, description)
    let targetValues = node.overlayTargets(description)
    var ruleSelectors: seq[Selector]
    for targetValue in targetValues:
      for selector in targetValue.parseSelector:
        ruleSelectors.add selector
    ruleSelectors.sort(proc(left, right: Selector): int =
      cmp(left.source, right.source))
    for selectorIndex in 1..<ruleSelectors.len:
      if ruleSelectors[selectorIndex - 1].source ==
          ruleSelectors[selectorIndex].source:
        overlayFailure(
          description & " repeats selector: " &
            ruleSelectors[selectorIndex].source
        )
    var targetParts: seq[string]
    for selector in ruleSelectors:
      targetParts.add selector.source
    let target = targetParts.join("|")
    if target in targets:
      overlayFailure("duplicate overlay target: " & target)
    targets.incl target
    let semantic = parseSemantic(node.overlayString("semantic", description))
    let representation = parseRepresentation(
      node.overlayString("representation", description)
    )
    validateSemanticPair(semantic, representation)
    result.rules.add OverlayRule(
      target: target,
      semantic: semantic,
      representation: representation,
      reason: node.overlayString("reason", description),
    )
    selectors.add ruleSelectors

  var segments: seq[string]
  var locations: seq[JsonLocation]
  collectJsonLocations(spec, segments, locations)
  var ownerByPointer = initTable[string, int]()

  for ruleIndex in 0..<result.rules.len:
    var matchesByPointer = initTable[string, JsonLocation]()
    for selector in selectors[ruleIndex]:
      var alternativeMatches = 0
      for location in locations:
        if selector.matches(location):
          validateSemanticNode(
            result.rules[ruleIndex], selector.source, location
          )
          inc alternativeMatches
          if matchesByPointer.hasKey(location.pointer):
            overlayFailure(
              "selector alternatives overlap at " & location.pointer &
                " in target " & result.rules[ruleIndex].target
            )
          matchesByPointer[location.pointer] = location
      if alternativeMatches == 0:
        overlayFailure(
          "selector alternative matched no OpenAPI location: " &
            selector.source
        )

    var pointers: seq[string]
    for pointer in matchesByPointer.keys:
      pointers.add pointer
    pointers.sort
    result.rules[ruleIndex].matchCount = pointers.len

    for pointer in pointers:
      if ownerByPointer.hasKey(pointer):
        let previousIndex = ownerByPointer[pointer]
        let previous = result.rules[previousIndex]
        let current = result.rules[ruleIndex]
        if previous.semantic == current.semantic and
            previous.representation == current.representation:
          overlayFailure(
            "duplicate semantic match at " & pointer & " from rules " &
              $previousIndex & " and " & $ruleIndex
          )
        overlayFailure(
          "conflicting semantic match at " & pointer & " from rules " &
            $previousIndex & " and " & $ruleIndex
        )
      ownerByPointer[pointer] = ruleIndex
      let location = matchesByPointer[pointer]
      let rule = result.rules[ruleIndex]
      result.descriptors.add OverlayDescriptor(
        jsonPointer: pointer,
        schemaName: descriptorSchemaName(location.segments),
        propertyName: descriptorPropertyName(location.segments),
        semantic: rule.semantic,
        representation: rule.representation,
        reason: rule.reason,
        ruleIndex: ruleIndex,
      )

  result.descriptors.sort(proc(
      left, right: OverlayDescriptor
  ): int = cmp(left.jsonPointer, right.jsonPointer))

proc findProjectRoot(start: string): string =
  var candidate = start.absolutePath
  while true:
    if fileExists(candidate / "schemas" / "schema-lock.json"):
      return candidate
    let parent = candidate.parentDir
    if parent == candidate:
      break
    candidate = parent

proc projectRoot(): string =
  result = findProjectRoot(getCurrentDir())
  if result.len == 0:
    result = findProjectRoot(getAppDir())
  if result.len == 0:
    fail "could not find schemas/schema-lock.json"

proc readLock(root: string): LockInfo =
  let node = parseFile(root / "schemas" / "schema-lock.json")
  result.apiVersion = node.requiredInt("apiVersion")
  result.schemaRevision = node.requiredString("schemaRevision")
  result.sourceRepository = node.requiredString("sourceRepository")
  result.sourceCommit = node.requiredString("sourceCommit")
  result.specRelativePath = node.requiredString("standardSpec")
  result.specSha256 = node.requiredString("standardSpecSha256")
  result.overlayRelativePath = node.requiredString("overlay")
  result.overlayRevision = node.requiredInt("overlayRevision")

func nimQuote(value: string): string =
  result = "\""
  for character in value:
    case character
    of '\\': result.add "\\\\"
    of '"': result.add "\\\""
    of '\n': result.add "\\n"
    of '\r': result.add "\\r"
    of '\t': result.add "\\t"
    else: result.add character
  result.add '"'

func snakeName(value: string): string =
  var needsSeparator = false
  for character in value:
    if character in {'a'..'z', '0'..'9'}:
      if needsSeparator and result.len > 0 and result[^1] != '_':
        result.add '_'
      result.add character
      needsSeparator = false
    elif character in {'A'..'Z'}:
      if needsSeparator and result.len > 0 and result[^1] != '_':
        result.add '_'
      result.add character.toLowerAscii
      needsSeparator = false
    else:
      needsSeparator = true
  if result.len == 0:
    result = "other"
  if result[0] in {'0'..'9'}:
    result = "resource_" & result

func lowerCamel(value: string): string =
  var capitalizeNext = false
  for character in value:
    if character in {'a'..'z', 'A'..'Z', '0'..'9'}:
      if result.len == 0:
        result.add character.toLowerAscii
      elif capitalizeNext:
        result.add character.toUpperAscii
      else:
        result.add character
      capitalizeNext = false
    else:
      capitalizeNext = true
  if result.len == 0 or result[0] in {'0'..'9'}:
    result = "route" & result

func typeName(value: string): string =
  var capitalizeNext = true
  for character in value:
    if character in {'a'..'z', 'A'..'Z', '0'..'9'}:
      if capitalizeNext:
        result.add character.toUpperAscii
      else:
        result.add character
      capitalizeNext = false
    else:
      capitalizeNext = true
  if result.len == 0 or result[0] in {'0'..'9'}:
    result = "Schema" & result

func referenceName(reference: string): string =
  let separator = reference.rfind('/')
  if separator >= 0:
    reference[separator + 1 .. ^1]
  else:
    reference

proc schemaLabel(schema: JsonNode): string =
  if schema.isNil or schema.kind != JObject:
    return ""
  if schema.hasKey("$ref") and schema["$ref"].kind == JString:
    return referenceName(schema["$ref"].getStr)
  if schema.hasKey("type"):
    let kind = schema["type"]
    if kind.kind == JString:
      if kind.getStr == "array" and schema.hasKey("items"):
        return "seq[" & schemaLabel(schema["items"]) & "]"
      return kind.getStr
    if kind.kind == JArray:
      var alternatives: seq[string]
      for value in kind.items:
        if value.kind == JString:
          if value.getStr == "array" and schema.hasKey("items"):
            alternatives.add "seq[" & schemaLabel(schema["items"]) & "]"
          else:
            alternatives.add value.getStr
      return alternatives.join(" | ")
  for unionKey in ["oneOf", "anyOf", "allOf"]:
    if schema.hasKey(unionKey) and schema[unionKey].kind == JArray:
      var alternatives: seq[string]
      for alternative in schema[unionKey].items:
        let label = schemaLabel(alternative)
        if label.len > 0 and label notin alternatives:
          alternatives.add label
      if alternatives.len > 0:
        return alternatives.join(" | ")
  "inline"

proc contentSchema(container: JsonNode): string =
  if container.isNil or container.kind != JObject:
    return ""
  if container.hasKey("$ref"):
    return schemaLabel(container)
  if not container.hasKey("content") or container["content"].kind != JObject:
    return ""
  let content = container["content"]
  for mediaType in ["application/json", "multipart/form-data"]:
    if content.hasKey(mediaType):
      let media = content[mediaType]
      if media.kind == JObject and media.hasKey("schema"):
        return schemaLabel(media["schema"])
  for mediaType in content.sortedKeys:
    let media = content[mediaType]
    if media.kind == JObject and media.hasKey("schema"):
      return schemaLabel(media["schema"])

proc responseSchema(operation: JsonNode): string =
  if not operation.hasKey("responses") or
      operation["responses"].kind != JObject:
    return ""
  let responses = operation["responses"]
  for status in responses.sortedKeys:
    if status.len == 3 and status[0] == '2':
      let label = contentSchema(responses[status])
      if label.len > 0:
        return label

func resourceName(path: string): string =
  let start = if path.len > 0 and path[0] == '/': 1 else: 0
  let separator = path.find('/', start)
  let raw = if separator < 0: path[start .. ^1]
    else: path[start..<separator]
  snakeName(raw)

func methodName(value: string): string =
  case value
  of "get": "httpGet"
  of "post": "httpPost"
  of "put": "httpPut"
  of "patch": "httpPatch"
  of "delete": "httpDelete"
  else: ""

proc collectOperations(spec: JsonNode): seq[Operation] =
  if not spec.hasKey("paths") or spec["paths"].kind != JObject:
    fail "OpenAPI document has no paths object"
  let paths = spec["paths"]
  for path in paths.sortedKeys:
    let pathItem = paths[path]
    for httpMethod in ["get", "post", "put", "patch", "delete"]:
      if pathItem.hasKey(httpMethod):
        let operation = pathItem[httpMethod]
        if not operation.hasKey("operationId"):
          fail httpMethod.toUpperAscii & " " & path & " has no operationId"
        let operationId = operation["operationId"].getStr
        let hasBody = operation.hasKey("requestBody")
        let request =
          if hasBody: contentSchema(operation["requestBody"])
          else: ""
        let deprecated = operation.hasKey("deprecated") and
          operation["deprecated"].kind == JBool and
          operation["deprecated"].getBool
        result.add Operation(
          resource: resourceName(path),
          path: path,
          httpMethod: httpMethod,
          operationId: operationId,
          nimName: lowerCamel(operationId),
          requestSchema: request,
          responseSchema: responseSchema(operation),
          hasRequestBody: hasBody,
          deprecated: deprecated
        )

func schemaCategory(name: string): string =
  if name.startsWith("Application") or name.startsWith("Activities") or
      name.startsWith("Activity") or name.startsWith("Entitlement") or
      name.startsWith("Sku") or name.startsWith("Subscription"):
    "application"
  elif name.startsWith("AuditLog"):
    "audit_log"
  elif name.startsWith("Automod") or name.startsWith("AutoModeration"):
    "automod"
  elif name.startsWith("Channel") or name.startsWith("Thread") or
      name.startsWith("Forum"):
    "channel"
  elif name.startsWith("Command"):
    "command"
  elif name.startsWith("Component") or name.startsWith("ActionRow") or
      name.startsWith("Button") or name.startsWith("TextDisplay") or
      name.startsWith("Section") or name.startsWith("Separator") or
      name.startsWith("Container") or name.startsWith("MediaGallery") or
      name.startsWith("Thumbnail") or name.startsWith("FileComponent") or
      name.startsWith("Label") or name.startsWith("Checkbox") or
      name.startsWith("RadioGroup"):
    "component"
  elif name.startsWith("Emoji"):
    "emoji"
  elif name.startsWith("Gateway"):
    "gateway"
  elif name.startsWith("Guild") or name.startsWith("Ban") or
      name.startsWith("Role") or name.startsWith("WelcomeScreen") or
      name.startsWith("Widget"):
    "guild"
  elif name.startsWith("Integration"):
    "integration"
  elif name.startsWith("Interaction") or name.contains("InteractionCallback"):
    "interaction"
  elif name.startsWith("Invite"):
    "invite"
  elif name.startsWith("Lobby"):
    "lobby"
  elif name.startsWith("Message") or name.startsWith("AllowedMention") or
      name.startsWith("Attachment") or name.startsWith("Embed"):
    "message"
  elif name.startsWith("OAuth2") or name.startsWith("OAuth"):
    "oauth2"
  elif name.startsWith("Poll"):
    "poll"
  elif name.startsWith("Soundboard") or name.startsWith("Sound"):
    "soundboard"
  elif name.startsWith("Stage"):
    "stage_instance"
  elif name.startsWith("Sticker"):
    "sticker"
  elif name.startsWith("User") or name.startsWith("Account"):
    "user"
  elif name.startsWith("Voice"):
    "voice"
  elif name.startsWith("Webhook") or name.startsWith("IncomingWebhook"):
    "webhook"
  else:
    "common"

func generatedHeader(lock: LockInfo): string =
  generatedFileMarker & "\n" &
    "# Source: " & lock.sourceRepository & " @ " & lock.sourceCommit & "\n" &
    "# Schema revision: " & lock.schemaRevision & "\n\n"

func generatedPreamble(lock: LockInfo; summary: string): string =
  "## " & summary & "\n" &
    "##\n" &
    "## This module is generated from Cordnim's pinned Discord OpenAPI " &
    "snapshot.\n" &
    "## Update `tools/schema_codegen.nim` or the semantic overlay instead of\n" &
    "## editing generated declarations.\n\n" &
    generatedHeader(lock)

proc addFile(files: var seq[GeneratedFile], path, content: string) =
  var normalized = content
  while normalized.endsWith("\n\n"):
    normalized.setLen(normalized.len - 1)
  files.add GeneratedFile(relativePath: path, content: normalized)

proc generateSchemaInfo(
    files: var seq[GeneratedFile], lock: LockInfo,
    schemaCount, operationCount: int; overlay: SemanticOverlayPlan
) =
  var content = generatedPreamble(
    lock,
    "Version and compatibility metadata for the generated raw API.",
  )
  content.add "const\n"
  content.add "  discordApiVersion* = " & $lock.apiVersion &
    " ## Discord REST API version targeted by this snapshot.\n"
  content.add "  discordSchemaRevision* = " & nimQuote(lock.schemaRevision) &
    " ## Revision date of the pinned Discord schema snapshot.\n"
  content.add "  discordSchemaSourceCommit* = " & nimQuote(lock.sourceCommit) &
    " ## Full commit hash in Discord's specification repository.\n"
  content.add "  discordSchemaSha256* = " & nimQuote(lock.specSha256) &
    " ## SHA-256 digest of the pinned OpenAPI document.\n"
  content.add "  discordOverlayRevision* = " & $lock.overlayRevision &
    " ## Revision of Cordnim's semantic corrections.\n"
  content.add "  discordOverlayDescription* = " &
    nimQuote(overlay.description) &
    " ## Human-readable purpose of the semantic overlay.\n"
  content.add "  discordOverlayRuleCount* = " & $overlay.rules.len &
    " ## Number of explicit semantic correction rules.\n"
  content.add "  discordOverlayDescriptorCount* = " &
    $overlay.descriptors.len &
    " ## Number of concrete OpenAPI locations corrected by the overlay.\n"
  content.add "  discordSchemaCount* = " & $schemaCount &
    " ## Number of component schemas in the snapshot.\n"
  content.add "  discordOperationCount* = " & $operationCount &
    " ## Number of generated stable HTTP operations.\n"
  content.add "  preservesUnknownObjectFields* = " &
    $overlay.constraints.preserveUnknownObjectFields &
    " ## Whether raw models round-trip unrecognized object fields.\n"
  content.add "  preservesUnknownEnumValues* = " &
    $overlay.constraints.preserveUnknownEnumValues &
    " ## Whether decoding retains unrecognized enum values.\n"
  content.add "  preservesUnknownFlagBits* = " &
    $overlay.constraints.preserveUnknownFlagBits &
    " ## Whether bit fields retain bits unknown to this revision.\n"
  content.add "  treatsOptionalAndNullableSeparately* = " &
    $overlay.constraints.treatOptionalAndNullableSeparately &
    " ## Whether omission and explicit null remain distinct states.\n"
  content.add "  componentsV2TransitionIsIrreversible* = " &
    $overlay.constraints.componentsV2Irreversible &
    " ## Whether Components V2 upgrades are modeled as one-way.\n"
  content.add "  maximumMessageComponents* = " &
    $overlay.constraints.maximumMessageComponents &
    " ## Maximum components accepted in one message tree.\n"
  content.add "  legacyAndV2MessageFieldsAreExclusive* = " &
    $overlay.constraints.legacyAndV2MessageFieldsExclusive &
    " ## Whether legacy and Components V2 message fields may coexist.\n"
  content.add "  discordOverlayRuleMatchCounts*: array[" &
    $overlay.rules.len & ", int] = [\n"
  for rule in overlay.rules:
    content.add "    " & $rule.matchCount & ",\n"
  content.add "  ] ## Concrete match count for each overlay rule in order.\n"
  files.addFile("src/cordnim/raw/schema_info.nim", content)

proc generateSemantics(
    files: var seq[GeneratedFile]; lock: LockInfo;
    overlay: SemanticOverlayPlan
) =
  var content = generatedPreamble(
    lock,
    "Applied semantic metadata for the generated raw Discord schema.",
  )
  content.add "import std/options\n\n"
  content.add "type\n"
  content.add "  SemanticKind* {.pure.} = enum\n"
  content.add "    Snowflake ## Unsigned Discord snowflake identifier.\n"
  content.add "    ExtensibleBits ## Arbitrary-width future-compatible flags.\n"
  content.add "    PatchObject ## Update object preserving omit/null/value.\n"
  content.add "    ExclusiveUnion ## Exactly one documented union branch.\n"
  content.add "    OpenEnum ## Known view over a losslessly retained value.\n"
  content.add "    IrreversibleComponentsV2Transition ## One-way V2 upgrade.\n"
  content.add "    LegalComponentTree ## Validated message component tree.\n"
  content.add "    ModalLabelTree ## Typed modal form and submission tree.\n\n"
  content.add "  SemanticRepresentation* {.pure.} = enum\n"
  content.add "    DecimalStringAtJsonBoundary ## Canonical decimal string.\n"
  content.add "    DecimalStringArbitraryWidth ## Unbounded decimal string.\n"
  content.add "    UnsetNullValue ## Three-state update representation.\n"
  content.add "    OneOf ## Exclusive union representation.\n"
  content.add "    RawValuePlusKnownView ## Raw enum plus optional " &
    "known view.\n"
  content.add "    SeparateLegacyAndV2Types ## Distinct message states.\n"
  content.add "    ValidatedParentChildTreeMax40 ## Checked message tree.\n"
  content.add "    TypedFormSchemaAndDecoder ## Checked modal form codec.\n\n"
  content.add "  SemanticRuleDescriptor* = object\n"
  content.add "    target*: string ## Original overlay selector.\n"
  content.add "    semantic*: SemanticKind ## Semantic correction.\n"
  content.add "    representation*: SemanticRepresentation ## Wire model.\n"
  content.add "    reason*: string ## Rationale recorded in the overlay.\n"
  content.add "    matchCount*: int ## Concrete locations matched.\n\n"
  content.add "  SemanticDescriptor* = object\n"
  content.add "    jsonPointer*: string ## Exact pointer in the OpenAPI file.\n"
  content.add "    schemaName*: string ## Component schema, when applicable.\n"
  content.add "    propertyName*: string ## Nearest property, when " &
    "applicable.\n"
  content.add "    semantic*: SemanticKind ## Semantic correction.\n"
  content.add "    representation*: SemanticRepresentation ## Wire model.\n"
  content.add "    reason*: string ## Rationale recorded in the overlay.\n"
  content.add "    ruleIndex*: int ## Index into `semanticRules`.\n\n"

  content.add "const semanticRules*: array[" & $overlay.rules.len &
    ", SemanticRuleDescriptor] = [\n"
  for rule in overlay.rules:
    content.add "  SemanticRuleDescriptor(\n"
    content.add "    target: " & nimQuote(rule.target) & ",\n"
    content.add "    semantic: SemanticKind." & $rule.semantic & ",\n"
    content.add "    representation: SemanticRepresentation." &
      $rule.representation & ",\n"
    content.add "    reason: " & nimQuote(rule.reason) & ",\n"
    content.add "    matchCount: " & $rule.matchCount & ",\n"
    content.add "  ),\n"
  content.add "] ## Validated overlay rules in source order.\n\n"

  content.add "const semanticDescriptors*: array[" &
    $overlay.descriptors.len & ", SemanticDescriptor] = [\n"
  for descriptor in overlay.descriptors:
    content.add "  SemanticDescriptor(\n"
    content.add "    jsonPointer: " & nimQuote(descriptor.jsonPointer) & ",\n"
    content.add "    schemaName: " & nimQuote(descriptor.schemaName) & ",\n"
    content.add "    propertyName: " &
      nimQuote(descriptor.propertyName) & ",\n"
    content.add "    semantic: SemanticKind." & $descriptor.semantic & ",\n"
    content.add "    representation: SemanticRepresentation." &
      $descriptor.representation & ",\n"
    content.add "    reason: " & nimQuote(descriptor.reason) & ",\n"
    content.add "    ruleIndex: " & $descriptor.ruleIndex & ",\n"
    content.add "  ),\n"
  content.add "] ## Every concrete semantic correction, sorted by pointer.\n\n"

  content.add "func findSemanticDescriptor*(\n"
  content.add "    jsonPointer: string\n"
  content.add "): Option[SemanticDescriptor] =\n"
  content.add "  ## Looks up the correction for an exact OpenAPI " &
    "JSON Pointer.\n"
  content.add "  for descriptor in semanticDescriptors:\n"
  content.add "    if descriptor.jsonPointer == jsonPointer:\n"
  content.add "      return some(descriptor)\n"
  content.add "  none(SemanticDescriptor)\n\n"

  content.add "func semanticDescriptorsForSchema*(\n"
  content.add "    schemaName: string\n"
  content.add "): seq[SemanticDescriptor] =\n"
  content.add "  ## Returns all corrections attached to a component schema.\n"
  content.add "  for descriptor in semanticDescriptors:\n"
  content.add "    if descriptor.schemaName == schemaName:\n"
  content.add "      result.add descriptor\n\n"

  content.add "func semanticDescriptorsForProperty*(\n"
  content.add "    schemaName, propertyName: string\n"
  content.add "): seq[SemanticDescriptor] =\n"
  content.add "  ## Returns corrections attached to a named schema property.\n"
  content.add "  for descriptor in semanticDescriptors:\n"
  content.add "    if descriptor.schemaName == schemaName and\n"
  content.add "        descriptor.propertyName == propertyName:\n"
  content.add "      result.add descriptor\n"
  files.addFile("src/cordnim/raw/semantics.nim", content)

proc generateModels(
    files: var seq[GeneratedFile], lock: LockInfo, schemas: JsonNode;
    overlay: SemanticOverlayPlan
) =
  var categories = initOrderedTable[string, seq[string]]()
  let schemaNames = schemas.sortedKeys
  for schemaName in schemaNames:
    let category = schemaCategory(schemaName)
    categories.mgetOrPut(category, @[]).add schemaName

  var categoryNames: seq[string]
  for category in categories.keys:
    categoryNames.add category
  categoryNames.sort

  for category in categoryNames:
    var content = generatedPreamble(
      lock,
      "Lossless raw Discord models in the `" & category & "` schema group.",
    )
    content.add "import std/json\n\n"
    content.add "type\n"
    for schemaName in categories[category]:
      let nimName = typeName(schemaName)
      content.add "  " & nimName &
        "* = object ## Lossless raw representation " &
        "of OpenAPI schema `" & schemaName & "`.\n"
      var descriptorCount = 0
      for descriptor in overlay.descriptors:
        if descriptor.schemaName == schemaName:
          inc descriptorCount
      if descriptorCount > 0:
        content.add "    ##\n"
        content.add "    ## Applied semantic overlay metadata:\n"
        for descriptor in overlay.descriptors:
          if descriptor.schemaName == schemaName:
            content.add "    ## - `" & descriptor.jsonPointer & "`\n"
            content.add "    ##   uses `" &
              descriptor.semantic.semanticWire & "` with `" &
              descriptor.representation.representationWire & "`.\n"
      content.add "    raw*: JsonNode ## Complete JSON payload, including " &
        "fields unknown to this schema revision.\n\n"
    files.addFile("src/cordnim/raw/models/" & category & ".nim", content)

  var index = generatedPreamble(
    lock,
    "Complete index of stable raw Discord OpenAPI models.",
  )
  index.add "import ./[model, semantics]\n"
  for category in categoryNames:
    index.add "import ./models/" & category & "\n"
  index.add "\nexport model, semantics\n"
  for category in categoryNames:
    index.add "export " & category & "\n"
  index.add "\nconst schemaNames*: array[" & $schemaNames.len &
    ", string] = [\n"
  for schemaName in schemaNames:
    index.add "  " & nimQuote(schemaName) & ",\n"
  index.add "] ## Canonical OpenAPI component names available in this " &
    "snapshot.\n"
  files.addFile("src/cordnim/raw/models.nim", index)

proc generateRoutes(
    files: var seq[GeneratedFile], lock: LockInfo,
    operations: seq[Operation]
) =
  var resources = initOrderedTable[string, seq[Operation]]()
  for operation in operations:
    resources.mgetOrPut(operation.resource, @[]).add operation

  var resourceNames: seq[string]
  for resource in resources.keys:
    resourceNames.add resource
  resourceNames.sort

  for resource in resourceNames:
    var content = generatedPreamble(
      lock,
      "Stable raw Discord HTTP routes in the `" & resource &
        "` resource group.",
    )
    content.add "import ../route\n\n"
    content.add "const\n"
    for operation in resources[resource]:
      content.add "  " & operation.nimName & "* = RawRoute(\n"
      content.add "    httpMethod: " & methodName(operation.httpMethod) & ",\n"
      content.add "    pathTemplate: " & nimQuote(operation.path) & ",\n"
      content.add "    operationId: " & nimQuote(operation.operationId) & ",\n"
      content.add "    requestSchema: " &
        nimQuote(operation.requestSchema) & ",\n"
      content.add "    responseSchema: " &
        nimQuote(operation.responseSchema) & ",\n"
      content.add "    hasRequestBody: " & $operation.hasRequestBody & ",\n"
      content.add "    deprecated: " & $operation.deprecated & "\n"
      content.add "  ) ## Route metadata for `" &
        operation.httpMethod.toUpperAscii & " " & operation.path & "` " &
        "(`" & operation.operationId & "`).\n"
    let inventoryName = lowerCamel(resource) & "Routes"
    content.add "  " & inventoryName & "*: array[" &
      $resources[resource].len & ", RawRoute] = [\n"
    for operation in resources[resource]:
      content.add "    " & operation.nimName & ",\n"
    content.add "  ] ## All generated routes in this resource group.\n"
    files.addFile("src/cordnim/raw/routes/" & resource & ".nim", content)

  var index = generatedPreamble(
    lock,
    "Complete registry of stable raw Discord HTTP routes.",
  )
  index.add "import std/options\n\n"
  index.add "import ./route\n"
  for resource in resourceNames:
    index.add "import ./routes/" & resource & "\n"
  index.add "\nexport route\n"
  for resource in resourceNames:
    index.add "export " & resource & "\n"
  index.add "\nconst allRoutes*: array[" & $operations.len & ", RawRoute] = [\n"
  for operation in operations:
    index.add "  " & operation.nimName & ",\n"
  index.add "] ## Every HTTP operation in the pinned stable schema.\n\n"
  index.add "func findRoute*(operationId: string): Option[RawRoute] =\n"
  index.add "  ## Looks up generated route metadata by its " &
    "OpenAPI operation ID.\n"
  index.add "  for route in allRoutes:\n"
  index.add "    if route.operationId == operationId:\n"
  index.add "      return some(route)\n"
  index.add "  none(RawRoute)\n"
  files.addFile("src/cordnim/raw/routes.nim", index)

proc generateRouteInventory(
    files: var seq[GeneratedFile], lock: LockInfo,
    operations: openArray[Operation]
) =
  var content =
    generatedFileMarker & "\n"
  content.add "# source_commit\t" & lock.sourceCommit & "\n"
  content.add "method\tpath\toperation_id\trequest_schema\tresponse_schema\n"
  for operation in operations:
    let requestSchema =
      if operation.requestSchema.len == 0: "-" else: operation.requestSchema
    let responseSchema =
      if operation.responseSchema.len == 0: "-" else: operation.responseSchema
    content.add operation.httpMethod.toUpperAscii & "\t"
    content.add operation.path & "\t"
    content.add operation.operationId & "\t"
    content.add requestSchema & "\t"
    content.add responseSchema & "\n"
  files.addFile("schemas/stable-routes.tsv", content)

proc generate(root: string): seq[GeneratedFile] =
  let lock = readLock(root)
  let specPath = root / "schemas" / lock.specRelativePath
  let overlayPath = root / "schemas" / lock.overlayRelativePath
  if not fileExists(specPath):
    fail "missing pinned spec: " & specPath
  if not fileExists(overlayPath):
    fail "missing semantic overlay: " & overlayPath

  let specText = readFile(specPath)
  let actualDigest = sha256Hex(specText)
  if actualDigest != lock.specSha256:
    fail "pinned spec SHA-256 mismatch: expected " & lock.specSha256 &
      ", got " & actualDigest

  let spec = parseJson(specText)
  let overlay = parseFile(overlayPath)
  if not spec.hasKey("info") or
      spec["info"].requiredString("version") != $lock.apiVersion:
    fail "OpenAPI info.version does not match schema lock"
  if not spec.hasKey("components") or
      not spec["components"].hasKey("schemas"):
    fail "OpenAPI document has no component schemas"

  let operations = collectOperations(spec)
  let schemas = spec["components"]["schemas"]
  let semanticOverlay = applySemanticOverlay(spec, overlay)
  if semanticOverlay.revision != lock.overlayRevision:
    fail "applied semantic overlay revision does not match schema lock"

  result.generateSchemaInfo(
    lock, schemas.len, operations.len, semanticOverlay
  )
  result.generateSemantics(lock, semanticOverlay)
  result.generateModels(lock, schemas, semanticOverlay)
  result.generateRoutes(lock, operations)
  result.generateRouteInventory(lock, operations)
  result.sort(proc(left, right: GeneratedFile): int =
    cmp(left.relativePath, right.relativePath))

func portableRelativePath(path: string): string =
  path.replace('\\', '/')

proc collectGeneratedOrphan(
    path, root: string; expected: HashSet[string];
    orphans: var seq[string]
) =
  if fileExists(path) and readFile(path).contains(generatedFileMarker):
    let relative = relativePath(path, root).portableRelativePath
    if relative notin expected:
      orphans.add relative

proc findGeneratedOrphans*(
    root: string; expectedRelativePaths: openArray[string]
): seq[string] =
  ## Finds generator-marked files that are absent from the expected manifest.
  ##
  ## The raw source tree is scanned recursively because generated model and
  ## route groups may disappear after a schema update. Only top-level schema
  ## artifacts are scanned; the pinned upstream snapshot is not generator
  ## output.
  var expected = initHashSet[string]()
  for path in expectedRelativePaths:
    expected.incl path.portableRelativePath

  let rawRoot = root / "src" / "cordnim" / "raw"
  if dirExists(rawRoot):
    for path in walkDirRec(rawRoot):
      collectGeneratedOrphan(path, root, expected, result)

  let schemaRoot = root / "schemas"
  if dirExists(schemaRoot):
    for kind, path in walkDir(schemaRoot):
      if kind == pcFile:
        collectGeneratedOrphan(path, root, expected, result)
  result.sort

proc applyGeneratedFiles(
    root: string, files: openArray[GeneratedFile], checkOnly: bool
) =
  var drift: seq[string]
  for generated in files:
    let path = root / generated.relativePath
    let current = if fileExists(path): readFile(path) else: ""
    if current != generated.content:
      if checkOnly:
        drift.add generated.relativePath
      else:
        createDir(path.parentDir)
        writeFile(path, generated.content)
        echo "generated ", generated.relativePath

  var expectedPaths: seq[string]
  for generated in files:
    expectedPaths.add generated.relativePath
  let orphans = findGeneratedOrphans(root, expectedPaths)
  for path in orphans:
    if checkOnly:
      stderr.writeLine "orphaned generated file: ", path
    else:
      stderr.writeLine "retained orphaned generated file: ", path

  if drift.len > 0 or (checkOnly and orphans.len > 0):
    for path in drift:
      stderr.writeLine "generated file differs: ", path
    quit "schema_codegen: generated files are stale"
  if checkOnly:
    echo "schema_codegen: generated files are current"

when isMainModule:
  let root = projectRoot()
  let checkOnly = "--check" in commandLineParams()
  try:
    let files = generate(root)
    applyGeneratedFiles(root, files, checkOnly)
  except OverlayError as error:
    fail error.msg
