## Version and compatibility metadata for the generated raw API.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot. Update `tools/schema_codegen.nim` or the semantic overlay instead of editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

const
  discordApiVersion* = 10 ## Discord REST API version targeted by this snapshot.
  discordSchemaRevision* = "2026-07-11" ## Cordnim release date assigned to the snapshot.
  discordSchemaSourceCommit* = "2c0a5ddffb9c9cf9b3a8826454758397a6b4804b" ## Full commit hash in Discord's specification repository.
  discordSchemaSha256* = "ce7cb08e4d2542ddba338315b1e78dc1bb7eaf16f8d298b582b70d61e259ea72" ## SHA-256 digest of the pinned OpenAPI document.
  discordOverlayRevision* = 2 ## Revision of Cordnim's semantic corrections.
  discordOverlayRuleCount* = 10 ## Number of explicit semantic correction rules.
  discordSchemaCount* = 538 ## Number of component schemas in the snapshot.
  discordOperationCount* = 242 ## Number of generated stable HTTP operations.
  preservesUnknownObjectFields* = true ## Whether raw models round-trip unrecognized object fields.
  preservesUnknownEnumValues* = true ## Whether decoding retains unrecognized enum values.
  preservesUnknownFlagBits* = true ## Whether bit fields retain bits unknown to this revision.
