## Version and compatibility metadata for the generated raw API.
##
## This module is generated from Cordnim's pinned Discord OpenAPI snapshot.
## Update `tools/schema_codegen.nim` or the semantic overlay instead of
## editing generated declarations.

# Generated by tools/schema_codegen.nim; do not edit by hand.
# Source: https://github.com/discord/discord-api-spec @ 2c0a5ddffb9c9cf9b3a8826454758397a6b4804b
# Schema revision: 2026-07-11

const
  discordApiVersion* = 10 ## Discord REST API version targeted by this snapshot.
  discordSchemaRevision* = "2026-07-11" ## Revision date of the pinned Discord schema snapshot.
  discordSchemaSourceCommit* = "2c0a5ddffb9c9cf9b3a8826454758397a6b4804b" ## Full commit hash in Discord's specification repository.
  discordSchemaSha256* = "ce7cb08e4d2542ddba338315b1e78dc1bb7eaf16f8d298b582b70d61e259ea72" ## SHA-256 digest of the pinned OpenAPI document.
  discordOverlayRevision* = 3 ## Revision of Cordnim's semantic corrections.
  discordOverlayDescription* = "Semantic corrections applied after parsing Discord's preview OpenAPI document." ## Human-readable purpose of the semantic overlay.
  discordOverlayRuleCount* = 10 ## Number of explicit semantic correction rules.
  discordOverlayDescriptorCount* = 231 ## Number of concrete OpenAPI locations corrected by the overlay.
  discordSchemaCount* = 538 ## Number of component schemas in the snapshot.
  discordOperationCount* = 242 ## Number of generated stable HTTP operations.
  preservesUnknownObjectFields* = true ## Whether raw models round-trip unrecognized object fields.
  preservesUnknownEnumValues* = true ## Whether decoding retains unrecognized enum values.
  preservesUnknownFlagBits* = true ## Whether bit fields retain bits unknown to this revision.
  treatsOptionalAndNullableSeparately* = true ## Whether omission and explicit null remain distinct states.
  componentsV2TransitionIsIrreversible* = true ## Whether Components V2 upgrades are modeled as one-way.
  maximumMessageComponents* = 40 ## Maximum components accepted in one message tree.
  legacyAndV2MessageFieldsAreExclusive* = true ## Whether legacy and Components V2 message fields may coexist.
  discordOverlayRuleMatchCounts*: array[10, int] = [
    1,
    12,
    3,
    8,
    16,
    157,
    6,
    1,
    14,
    13,
  ] ## Concrete match count for each overlay rule in order.
